.github/workflows/build-kc.yml, .github/workflows/code-check-test.yml, .github/workflows/generate-kcctl-docs.yml, .github/workflows/release.yml, Makefile, deploy/kcctl-docs.yaml, pkg/utils/sysutil/net_linux_test.go
/kind flake
add some github actions, and fix a test bug.
```
```
```release-note
None
```
```docs
```
=> add workflows

.github/workflows/test-coverage.yml, Makefile
/kind bug
/kind flake
Fixes #11 
```
```
```release-note
None
```
```docs
```
=> github action integrate codecov

pkg/component/nfs/nfs.go, pkg/scheme/core/v1/cri/containerd.go, pkg/scheme/core/v1/cri/docker.go, pkg/scheme/core/v1/k8s/cluster.go, pkg/scheme/core/v1/k8s/kubeadm.go, pkg/service/delivery/delivery.go, pkg/utils/cmdutil/cmdutil.go
/kind bug
Fixes #22 
```
```
```release-note
None
```
```docs
```
=> fix deleting abnormal k8s cluster

pkg/apis/core/v1/handler.go, pkg/apis/core/v1/utils.go, pkg/apis/core/v1/utils_test.go, pkg/controller/cronbackupcontroller/controller.go, pkg/scheme/core/v1/backup_types.go
/kind bug
Fixes #8 
```
```
```release-note
```
```docs
```
=> fix: Backup points cannot be deleted when in use

pkg/cli/deploy/deploy.go
/kind bug
Fixes #45 
```
```
```release-note
None
```
```docs
```
=> fix kcctl the default installation package path is incorrect

.github/PULL_REQUEST_TEMPLATE.md
/kind bug
Fixes #24 
```
```
```release-note
None
```
```docs
```
=> fix PR template have irrelevant keywords

pkg/apis/config/v1/handler.go, pkg/controller/cluster_status.go, pkg/server/config.go
/kind bug
Solve the problem that the node terminal function is not available
Fixes #
```
```
```release-note
None
```
```docs
```
=> fix get terminal encrypt key error

pkg/cli/registry/registry.go, pkg/cli/resource/resource.go
/kind bug
Fixes #50 
```
```
```release-note
None
```
```docs
```
=> fix kcctl registry and resource subcommand

pkg/scheme/core/v1/cri/containerd_test.go, pkg/scheme/core/v1/cri/template.go
/kind bug
containerd sanbox image mirror should same with localRegistry rather than insecureRegistry
Fixes #
```
```
```release-note
None
```
```docs
```
/cc @zhuzhenfan @qinyer
=> Fix containerd template render

cmd/kcctl/app/options/options.go, cmd/kubeclipper-agent/app/options/options.go, kubeclipper-agent.yaml, pkg/agent/agent.go, pkg/agent/config/config.go, pkg/cli/config/template.go, pkg/cli/deploy/deploy.go, pkg/cli/join/join.go, pkg/component/ctx.go, pkg/scheme/core/v1/cri/containerd.go, pkg/scheme/core/v1/k8s/kubeadm.go, pkg/scheme/core/v1/k8s/kubeadm_step.go, pkg/scheme/core/v1/k8s/template.go, pkg/service/task/handler.go, pkg/service/task/service.go, pkg/simple/imageproxy/options.go
/kind feature
Fixes #47 
```
```
```release-note
1. When you run the KCCTL quick installation script, you can set the KC_REGION environment variable in advance. The script dynamically generates the repo mirror env file based on the value of the variable.
2. Currently supported KC_REGION=cn, then the script automatically sets the third-party repo mirror proxy.
3. Users can set KC_IMAGE_REPO_MIRROR variable to customize the third-party repo mirror proxy.
```
```docs
```
=> feat: add the K8S mirror proxy setting option

pkg/apis/core/v1/handler.go
/kind bug
Fixes #25 
```
```
```release-note
None
```
```docs
```
=> fix creating a backup log record with the same name

pkg/controller/cronbackupcontroller/controller.go
Signed-off-by: liuchuwei <liu.chuwei@99cloud.net>
/kind bug
BackupPoint and cronBackup of back-end service logs reporting errors
Fixes # https://github.com/kubeclipper-labs/kubeclipper/issues/59
```
```
```release-note
None
```
```docs
```
=> update cronbackup controller

pkg/apis/core/v1/handler.go, pkg/controller/cronbackupcontroller/controller.go, pkg/scheme/core/v1/operation_types.go, pkg/service/delivery/delivery.go
Signed-off-by: liuchuwei <liu.chuwei@99cloud.net>
/kind bug
The operation name of the deleted backup is wrong
Fixes # https://github.com/kubeclipper-labs/kubeclipper/issues/66
```
```
```release-note
None
```
```docs
```
=> fix: delete backup operation name error

cmd/kcctl/app/options/options.go, pkg/agent/agent.go, pkg/agent/config/config.go, pkg/cli/config/template.go, pkg/cli/deploy/deploy.go, pkg/cli/join/join.go, pkg/nodestatus/node_status.go, pkg/scheme/core/v1/k8s/cluster.go, pkg/scheme/core/v1/k8s/kubeadm.go, pkg/service/task/service.go, pkg/utils/autodetection/filtered.go, pkg/utils/autodetection/filtered_test.go, pkg/utils/autodetection/interface.go, pkg/utils/autodetection/method.go, pkg/utils/autodetection/method_test.go, pkg/utils/netutil/netutil_linux.go, pkg/utils/netutil/netutil_linux_test.go
/kind feature
add kc-agent ip-detect method config.
Fixes #
```
kcctl deploy / join add an ip-detect flag to config kc-agent's ip-detect method.
kc-agent read /etc/kubeclipper-agent/kubeclipper-agent.yaml file to get ip-detect method when need. such as install k8s, kc-agent will get the ip-detect method to find the current node's ip.
```
```release-note
kcctl deploy / join add an ip-detect flag
```
```docs
```
=> feat: add ip detect config

pkg/utils/netutil/netutil_linux.go
/kind bug
avoid got a wrong default gateway.
Fixes #
```
before
when the default gateway is not first elements will get a wrong value, And if no default gateway will get another gateway as result.
```
```release-note
None
```
```docs
```
=> fix: avoid got a wrong default gateway.

pkg/apis/core/v1/handler.go, pkg/controller/clustercontroller/controller.go, pkg/controller/cronbackupcontroller/controller.go, pkg/models/cluster/cluster.go, pkg/models/cluster/interface.go, pkg/models/cluster/mock/mock_cluster.go, pkg/server/registry/cronbackup/strategy.go, pkg/server/server.go
/kind bug
Cron backups are not deleted when the cluster is deleted.
Fixes https://github.com/kubeclipper-labs/kubeclipper/issues/68
```
@x893675 @zhuzhenfan 
```
```release-note
None
```
```docs
```
=> fix: cron backups are not deleted when the cluster is deleted

cmd/kcctl/app/options/options.go, pkg/cli/deploy/deploy.go, pkg/cli/join/join.go, pkg/cli/sudo/sudo.go
/kind flake
add ip detect precheck, print a hint if the node has multi nic but --ip-detect not specified.
Fixes #
```
use cmd ip a|grep ": "|awk {'print $2'}|sed 's/://' to print ifaces.
filter logic iface, if > 1,print a hint.
```
```release-note
None
```
```docs
```
=> fix: add ip detect precheck

pkg/cli/deploy/deploy.go
/kind cleanup
Fixes #80 
```
```
```release-note
```
```docs
```
=> unnecessary /kc/configs directory

pkg/apis/core/v1/registry.go, pkg/apis/core/v1/schema.go, pkg/apis/core/v1/schema_test.go, pkg/controller/cluster_status.go, pkg/scheme/core/v1/k8s/kubeadm_step.go, pkg/scheme/core/v1/k8s/node.go
/kind bug
Fixes #90 
```
```
```release-note
None
```
```docs
```
=> fix: adding nodes and loading CNI images in the K8S cluster

pkg/apis/core/v1/handler.go
/kind bug
Fixes https://github.com/kubeclipper-labs/kubeclipper/issues/95
```
@x893675 
```
```release-note
None
```
```docs
```
=> fix: the name of the backup is the cluster name

pkg/server/config.go
/kind bug
Fixes #106
```
```
```release-note
None
```
```docs
```
=>  fix: add template-view permission to role cluster-view.

test/e2e/cluster/cluster_ha.go
/kind flake
add create HA cluster e2e test spec
Fixes #87 
```
```
```
None
```
```docs
```
=> feat: add create HA cluster e2e test spec

pkg/apis/core/v1/utils.go
/kind bug
Remove the action restriction of initComponentExtraCluster
Fixes #119 
```
```
```release-note
None
```
```docs
```
@x893675 @Xvv-v
=> fix: Remove the action restriction of initComponentExtraCluster

pkg/authentication/auth/token.go, pkg/authentication/oauth/oauth_options.go
/kind optimize
Fixes #123 
```
```
```release-note
None
```
```docs
```
=> add refresh token expires in login response

pkg/apis/oauth/handler.go
Fixes #97 
```
```
```release-note
None
```
```docs
```
=> add oauth login record

pkg/scheme/core/v1/k8s/cluster.go
/kind bug
Fixes #140
```
in install step hash chmod,upgrade step forgot.
```
```release-note
None
```
```docs
```
=> fix: cluster upgrade

pkg/component/nfs/nfs.go, pkg/simple/client/kc/api.go, pkg/simple/client/kc/request.go, pkg/simple/client/kc/scheme.go, test/e2e/cluster/backup.go, test/e2e/cluster/cluster_aio.go, test/e2e/cluster/component.go, test/e2e/cluster/recovery.go, test/e2e/demo/framework.go, test/framework/cluster/wait.go, test/framework/timeouts.go
/kind feature
Fixes #61 
```
```
```release-note
```
```docs
```
=> backup / recovery and install / uninstall component e2e test

Makefile
Fixes #
```
```
```release-note
None
```
```docs
```
=> add --tags for go cmd

go.mod, go.sum, pkg/scheme/core/v1/cri/containerd.go, pkg/scheme/core/v1/cri/containerd_test.go, pkg/scheme/core/v1/cri/cri.go, pkg/scheme/core/v1/cri/template.go
/kind bug
containerd uses an outdated configuration file
Fixes #121
```
```
```release-note
None
```
```docs
```
=> fix: update containerd config

Makefile, hack/lib/golang.sh, pkg/scheme/core/v1/k8s/script.go, pkg/scheme/core/v1/k8s/script_unchage.go
/kind bug
Fixes #
```
```
```release-note
None
```
```docs
```
=> refactor build tag

pkg/cli/registry/registry.go
/kind bug
update registry cmd to remove legacy files when clean registry.
Fixes #157
```
1. remote legacy files when registry clean cmd.
2. don't remove `/var/run/docker.sock` when user don't specify  --remove-docker flag.
```
```release-note
None
```
```docs
```
=> fix: registry cmd remove legacy files

pkg/scheme/core/v1/k8s/template.go
/kind bug
Fixes #163 
```
```
```release-note
```
```docs
```
=> fix: calico v3.22.4 config template image registry is not set

pkg/cli/clean/clean.go, pkg/cli/create/create.go, pkg/cli/delete/delete.go, pkg/cli/drain/drain.go, pkg/cli/get/get.go, pkg/cli/join/join.go, pkg/cli/login/login.go, pkg/cli/registry/registry.go, pkg/cli/resource/resource.go, pkg/cli/resource/resource_test.go
/kind flake
Fixes #
```
kcctl resource cmd remove unnecessary ssh parameter,load from deploy-config.yaml
```
```release-note
None
```
```docs
```
=> fix: kcctl resource remove unnecessary ssh parmeter.

pkg/cli/deploy/deploy.go, pkg/cli/drain/drain.go, pkg/cli/join/join.go, pkg/cli/proxy/deploy.go, pkg/cli/proxy/tunnel.go, pkg/cli/upgrade/upgrade.go, pkg/cli/utils/download.go, pkg/cli/utils/file.go, pkg/utils/sshutils/cmd.go, pkg/utils/sshutils/cmd_test.go, pkg/utils/sshutils/scp.go, pkg/utils/sshutils/ssh.go, pkg/utils/sshutils/ssh2cmd.go, pkg/utils/sshutils/ssh_v2.go, pkg/utils/sshutils/ssh_v2_test.go, pkg/utils/sshutils/sshcmd.go
/kind bug
update aio deploy without ssh config
Fixes #122
```
if user don't provide enough config for run ssh cmd,change to run cmd by os.exec on localhost.
and filecopy method from`github.com/pkg/sftp`lib change to  scp. 
remove some unused code.
```
```release-note
None
```
```docs
```
=> fix: update aio deploy without ssh config.

pkg/cli/deploy/deploy.go, pkg/cli/drain/drain.go, pkg/cli/join/join.go, pkg/cli/utils/download.go, pkg/cli/utils/file.go, pkg/controller/cronbackupcontroller/controller_test.go, pkg/utils/sshutils/cmd.go, pkg/utils/sshutils/cmd_test.go, pkg/utils/sshutils/scp.go, pkg/utils/sshutils/ssh.go, pkg/utils/sshutils/ssh2cmd.go, pkg/utils/sshutils/ssh_v2.go, pkg/utils/sshutils/ssh_v2_test.go, pkg/utils/sshutils/sshcmd.go
/kind bug
cherry-pick from #160 
Fixes #175 
```
```
```release-note
None
```
```docs
```
=> [release-1.1] fix: update aio deploy without ssh config.

pkg/controller/cronbackupcontroller/controller.go, pkg/controller/cronbackupcontroller/controller_test.go, pkg/server/server.go
/kind feature
update the way to parse month-end cron schedule
Fixes https://github.com/kubeclipper-labs/kubeclipper/issues/177
```
```
```release-note
None
```
```docs
```
@x893675
=> update cron schedule parse and unit test

pkg/controller/cronbackupcontroller/controller.go, pkg/controller/cronbackupcontroller/controller_test.go, pkg/server/server.go
* fix unit test
* update parse month-end cron schedule 2022/9/2 final.
Co-authored-by: Liucw <liu.chuwei@99cloud.net>
/kind feature
update cron schedule parse and unit test
Fixes https://github.com/kubeclipper-labs/kubeclipper/issues/179
```
```
```release-note
None
```
```docs
```
=> update cron schedule parse and unit test (#178)

pkg/scheme/core/v1/k8s/script.go
/kind optimize
Fixes #136 
```
```
```release-note
None
```
```docs
```
=> update kernel parameter

pkg/cli/proxy/deploy.go, pkg/proxy/proxy.go
/kind bug
Fixes #
```
untar kc-linux-xxx.tar.gz and mv kubeclipper-proxy to /usr/local/bin
diff arch tar package has diff layer，compatible this by tar cmd's --strip-components flag.
```
```release-note
None
```
```docs
```
=> fix: update proxy deploy cmd's untar path.

pkg/apis/core/v1/handler.go, pkg/apis/core/v1/registry.go
/kind bug
Fixes https://github.com/kubeclipper-labs/kubeclipper/issues/171
```
```
```release-note
None
```
```docs
```
=> fix: create renamed template without reporting error 

pkg/scheme/core/v1/k8s/kubeadm.go, pkg/scheme/core/v1/k8s/kubeadm_step.go
/kind bug
Fixes #186 
```
```
```release-note
```
```docs
```
=> kubeadm join node failed

pkg/scheme/core/v1/k8s/kubeadm_step.go
/kind bug
Fixes #192
some step need latest step,s response ,so there is a check
```go
if len(operation.Status.Conditions[i-1].Status) < 1 {
return errors.New("unexpected error, steps node field must be valid")
}
```
and will generte `Status.Conditions[i-1].Status` by `        cond.Status := make([]v1.StepStatus, len(step.Nodes))`
so，if step.Nodes == nil, len(cond.Status) is 0,and will retrun error on `if len(operation.Status.Conditions[i-1].Status) < 1 ` check.
installCNI setp caller like this:
```go 
steps, err = cn.InitStepper(&stepper.Cluster.CNI, &stepper.Cluster.Networking).InstallSteps(patchNodes, nil, true)
```
**second args is nil.**
installCNI setp like this:
```go
func (stepper *CNIInfo) InstallSteps(allNodes, firstMasterNodes …
```
=> fix: join node's installCNI step failed.

pkg/apis/core/v1/handler.go, pkg/apis/core/v1/utils.go, pkg/controller/cluster_status.go, pkg/scheme/core/v1/k8s/kubeadm_step.go
/kind bug
Fixes #114 
```
```
```release-note
```
```docs
```
=> Failed to update the K8S cluster certificate

pkg/cli/deploy/deploy.go
/kind bug
Fixes #196 
```
```
```release-note
```
```docs
```
=> fix: update search time service keywords

pkg/apis/core/v1/handler.go, pkg/models/cluster/cluster.go, pkg/models/models.go
/kind bug
Duplicate cron backup with same name for different clusters will report an error.
Fixes https://github.com/kubeclipper-labs/kubeclipper/issues/187
```
```
```release-note
None
```
```docs
```
@x893675
=> fix: create conbackups with same name between clusters error

pkg/component/utils/utils.go
/kind bug
Fixes #203 
```
```
```release-note
```
```docs
```
=> ctr image import added --all-platforms flags

cmd/kcctl/app/options/options.go, pkg/cli/deploy/deploy.go, pkg/utils/sshutils/ssh.go
/kind feature
Fixes https://github.com/kubeclipper-labs/kubeclipper/issues/191
```
```
```release-note
None
```
```docs
```
@x893675
=> add kcctl conection port configurable

cmd/kcctl/app/options/options.go, pkg/cli/deploy/deploy.go, pkg/cli/deploy/deploy_test.go, pkg/cli/get/get.go, pkg/server/config.go
/kind optimize
Fixes #
```
move render server and agent config template to DeployConfig struct
copy server and agent to server resource path
add get configmap subcommand to kcctl
```
```release-note
none
```
```docs
```
=> optimize deploy

api/openapi-spec/swagger.json, pkg/apis/core/v1/handler.go, pkg/apis/core/v1/registry.go, pkg/clustermanage/interface.go, pkg/clustermanage/mock/mock.go, pkg/controller/cloudpprovidercontroller/mock.go, pkg/server/config.go
/kind feature
add provider precheck api and permissions
Fixes #
```
```
```release-note
None
```
```docs
```
=> feat: add provider precheck api and permissions

pkg/scheme/core/v1/k8s/node.go
/kind bug
Fixes https://github.com/kubeclipper-labs/kubeclipper/issues/223
```
```
```release-note
None
```
```docs
```
@x893675
=> fix: drain istio node failed

pkg/apis/core/v1/utils.go, pkg/scheme/core/v1/k8s/cluster.go
/kind bug
after cluster recovery kubeproxy pod pengding
Fixes #234 
```
```
```release-note
None
```
```docs
```
=> fix: after cluster recovery kubeproxy pod pengding

pkg/scheme/core/v1/k8s/kubeadm.go, pkg/scheme/core/v1/k8s/kubeadm_step.go, pkg/scheme/core/v1/k8s/node.go, pkg/scheme/core/v1/k8s/template.go
/kind bug
Fixes #
```
```
```release-note
None
```
```docs
```
=> fix kubelet data dir do not take effect

pkg/cli/clean/clean.go, pkg/cli/registry/registry.go
/kind bug
Fixes #172 
```
```
```release-note
```
```docs
```
=> fix: kcctl clean kc env file

pkg/cli/deploy/deploy.go
/kind bug
Fixes #219
```
```
```release-note
```
```docs
```
=> fix: update the default package address for AIO

cmd/kubeclipper-agent/main.go, cmd/kubeclipper-server/main.go, pkg/apis/core/v1/handler.go, pkg/component/ctx.go, pkg/component/nfscsi/nfs_csi.go, pkg/component/nfscsi/template.go
/kind feature
support nfs csi
Fixes #
```
```
```release-note
None
```
```docs
```
=> feat: add nfs-csi

pkg/component/interface.go, pkg/component/nfs/nfs.go
/kind feature
Fixes #
```
```
```release-note
Add deprecated field
```
```docs
```
=> add deprecated field to mark plugin be deprecated

cmd/kcctl/app/options/options.go, pkg/authentication/options/options.go, pkg/cli/config/template.go, pkg/cli/deploy/deploy.go, pkg/controller/iam_status.go, pkg/server/server.go
/kind feature
Fixes #258 
```
```
```release-note
```
```docs
```
=> feat: loginRecord clean

pkg/apis/core/v1/handler.go
/kind flake
update error msg
Fixes #
```
```
```release-note
None
```
```docs
```
=> fix: update error msg

pkg/cli/deploy/deploy.go
/kind bug
Fixes #
```
```
```release-note
None
```
```docs
```
=> fix: deploy aio support master branch

cmd/kcctl/app/options/options.go, pkg/cli/registry/registry.go, pkg/cli/upgrade/upgrade.go, pkg/utils/sshutils/ssh.go
/kind bug
Fix the bug that the kcctl subcommand has a ssh port of 0.
Fixes #262 
```
@x893675 @Metrora 
```
```release-note
None
```
```docs
```
=> fix: kcctl subcommand has a bug where the ssh port is 0

README.md, README_zh.md
Signed-off-by: wu-wenxiang <wu-wenxiang@outlook.com>
=> doc: 1.2.0 -> 1.2.1 in readme

cmd/kcctl/app/options/options.go, pkg/utils/sshutils/ssh.go
/kind flake
make kcctl user friendly
Fixes #243
```
```
```release-note
None
```
```docs
```
=> fix: add human readable error msg

cmd/kubeclipper-server/app/options/options.go, pkg/client/clientrest/client.go, pkg/controller-runtime/manager/manager.go, pkg/server/server.go, pkg/service/staticresource/static_resource.go
/kind bug
http-server/static-file-server/controller-api start bind address update. Previously, the http server was listening to the 0.0.0.0 network segment, without listening to the network interface of the guide according to the configuration file
Fixes #246
```
@x893675 @qinyer 
```
```release-note
None
```
```docs
```
=> fix: http-server start bind address update

cmd/kcctl/app/options/options.go, pkg/apis/core/v1/handler.go, pkg/apis/core/v1/utils.go, pkg/cli/deploy/deploy.go, pkg/cli/deploy/deploy_test.go, pkg/cli/drain/drain.go, pkg/cli/join/join.go, pkg/cli/utils/file.go, pkg/clustermanage/kubeadm/provider.go, pkg/controller/cluster_status.go, pkg/controller/clustercontroller/controller.go
/kind bug
bug fix，compatible multiple nic
Fixes #201
```
deploy-config add agentID field
and used kcctl drain $agentID to drain
```
```release-note
None
```
```docs
```
=> fix: use agentID to drain node,compatible multiple nic

pkg/clustermanage/kubeadm/provider.go, pkg/clustermanage/kubeadm/wrapper.go
/kind bug
There is a known issue with k8s, where the node cri version information is incorrect when the cri type is docker
Fixes #280
```
```
```release-note
None
```
```docs
```
@x893675 @lixd
=> fix: Fix the bug that k8s gets incorrect docker version information

cmd/kcctl/app/options/options.go, pkg/apis/oauth/handler.go, pkg/apis/oauth/registry.go, pkg/authentication/options/options.go, pkg/cli/config/template.go, pkg/cli/deploy/deploy.go, pkg/server/server.go, tools/doc-gen/main.go
/kind feature
Fixes #286 
```
```
```release-note
```
```docs
```
=> feat: login auth rate limite

pkg/models/cluster/cluster.go, pkg/models/platform/platformsetting.go, pkg/models/platform/platformsetting_test.go
/kind feature
Fixes #
```
use `fuzzy~default-ip=xxx` to query node
use `fuzzy~ip=xxx` to query event
use `fuzzy~username=xxx` to query event
```
```release-note
None
```
```docs
```
=> add fuzzy search for node and event

pkg/clustermanage/kubeadm/provider.go
/kind bug
issue #294  Open again
Fixes #294 
```
```
```release-note
None
```
```docs
```
@x893675 @lixd
=> fix: determine if stderr is empty

pkg/apis/core/v1/handler.go, pkg/scheme/core/v1/backuppoint_types.go, test/e2e/cluster/backup.go
/kind bug
Fixes https://github.com/kubeclipper/kubeclipper/issues/310
```
```
```release-note
None
```
```docs
```
=> fix: edit no description s3 backuppoint error

api/openapi-spec/swagger.json, pkg/apis/core/v1/handler.go, pkg/apis/core/v1/registry.go, pkg/query/query.go, pkg/service/delivery/delivery.go, pkg/service/msg.go
/kind feature
Fixes #
```
```
```release-note
None
```
```docs
```
=> add ForceIgnoreError option to delivery service

pkg/apis/core/v1/handler.go, pkg/apis/core/v1/utils.go
/kind bug
reopen: check master node availability status before cluster recovery
Fixes #323 
```
@x893675 @Metrora 
```
```release-note
None
```
```docs
```
=> fix: cluster master node unhealthy before recovery without indication

pkg/apis/core/v1/handler.go, pkg/controller/cronbackupcontroller/controller.go
/kind bug
Fixes https://github.com/kubeclipper/kubeclipper/issues/328
```
```
```release-note
None
```
```docs
```
=> fix: The backup name is not the same as the backup file name

pkg/apis/core/v1/schema.go, pkg/scheme/core/v1/k8s/kubeadm_step.go, pkg/scheme/core/v1/k8s/node.go
/kind bug
Error adding nodes to nano import-cluster with cni limit. We usually think of cluster add/remove nodes as not necessarily related to cni
Fixes #329
```
@x893675 @qinyer 
```
```release-note
None
```
```docs
```
=> fix: Error adding nodes to nano import-cluster with cni limit

pkg/clustermanage/kubeadm/provider.go, pkg/scheme/core/v1/k8s/kubeadm.go, pkg/scheme/core/v1/k8s/template.go
/kind bug
Importing a cluster does not work with the kubectl terminal. The reason is that the kubectl pod proxy service is not runnin
Fixes #344
```
```
```release-note
None
```
```docs
```
@x893675 @lixd
=> Fix the bug that importing clusters cannot use kubectl terminal

test/e2e/cluster/cluster_aio.go, test/e2e/cluster/cluster_ha.go
/kind failing-test
/area testing
Fixes #
```
```
```release-note
None
```
```docs
```
=> fix create cluster e2e spec

pkg/apis/core/v1/handler.go, pkg/component/ctx.go, pkg/component/utils/utils.go, pkg/scheme/core/v1/k8s/node.go
when a worker node is added to a cluster, it is not useful to load the image of the addon component
/kind bug
When the worker node is added to the cluster, the image of the addon component is not loaded, resulting in the pod landing on the node without the corresponding addon image
Fixes #346
```
@x893675 @qinyer 
```
```release-note
None
```
```docs
```
=> fix: add worker node not install addon component

test/framework/test_context.go, test/framework/timeouts.go
/kind flake
/area testing
Fixes #
```
use  flag `cluster-install-short-timeout` set install aio cluster timeouts, default is 5m
e2e.test -cluster-install-short-timeout=10m -ginkgo.focus="AIO"
```
```release-note
None
```
```docs
```
=> add e2e spec install aio cluster timeout parameter

.github/workflows/test-aio.yml
/kind bug
Fixes #
```
```
```release-note
```
```docs
```
=> fix getting the target branch name

pkg/component/nfs/nfs.go, pkg/component/nfscsi/nfs_csi.go
/kind bug
Fixes https://github.com/kubeclipper/kubeclipper/issues/355
```
```
```release-note
None
```
```docs
```
=> fix: Failed to create one master one worker cluster with component without specifying the registry

api/openapi-spec/swagger.json, pkg/apis/core/v1/handler.go, pkg/apis/core/v1/registry.go, pkg/apis/iam/v1/handler.go, pkg/apis/iam/v1/registry.go, pkg/controller/projectcontroller/controller.go, pkg/query/query.go, pkg/server/config.go
/kind feature
Fixes #
```
add global resource's view api in project scope,and update roles
```
```release-note
None
```
```docs
```
=> fix: add global resource view api

pkg/apis/core/v1/handler.go, pkg/cli/delete/delete.go, pkg/cli/registry/registry.go, pkg/clustermanage/kubeadm/provider.go, pkg/simple/client/kc/api.go
/kind optimize
Fixes #
```
```
```release-note
None
```
```docs
```
=> add --force for kcctl delete cluster

pkg/apis/core/v1/handler.go, pkg/controller/cronbackupcontroller/controller.go, pkg/controller/cronbackupcontroller/controller_test.go
/kind feature
Fixes https://github.com/kubeclipper/kubeclipper/issues/365
```
```
```release-note
None
```
```docs
```
=> fix: The month-end cronbackup cannot be edited

pkg/apis/core/v1/handler.go, pkg/controller/cronbackupcontroller/controller.go, pkg/controller/cronbackupcontroller/controller_test.go
/kind bug
Fixes https://github.com/kubeclipper/kubeclipper/issues/365
```
```
```release-note
None
```
```docs
```
=> update the code of month-end cronbackup

pkg/apis/core/v1/handler.go, pkg/apis/core/v1/utils.go, pkg/cli/drain/drain.go, pkg/service/delivery/delivery.go
/kind optimize
Fixes #
```
```
```release-note
None
```
```docs
```
=> optimize force drain node and delete cluster

pkg/apis/core/v1/handler.go, pkg/apis/core/v1/utils.go, pkg/cli/drain/drain.go, pkg/service/delivery/delivery.go
fix auto cherrypick failed
Fixes #384 
```
```
```release-note
```
```docs
```
=> cherrypick: optimize force drain node and delete cluster (#382)

pkg/clustermanage/kubeadm/wrapper.go
/kind cleanup
import cluster remove local-registry。
The kc cluster usually inherits the cluster's local registry when installing the plugin without specifying it, causing the image pull to fail
Fixes #
```
```
```release-note
None
```
```docs
```
@x893675 @lixd
=> fix: import cluster remove local-registry

pkg/cli/create/create_cluster.go, pkg/cli/login/login.go
/kind bug
kcctl tool to create cluster, missing cartsans parameter
Fixes #391 
```
```
```release-note
None
```
```docs
```
@x893675 @lixd
=> kcctl tool to create cluster, missing cartsans parameter

pkg/cli/create/create_cluster.go
/kind bug
the kcctl tool to create a cluster is missing the project parameter
Fixes #394
```
```
```release-note
None
```
```docs
```
@x893675 @lixd
=> the kcctl tool to create a cluster is missing the project parameter

pkg/apis/core/v1/cri_utils.go, pkg/apis/core/v1/handler.go, pkg/apis/core/v1/utils.go, pkg/apis/core/v1/utils_test.go
/kind bug
Fixes #
```
```
```release-note
None
```
```docs
```
=> fix plugin cri registry

pkg/clustermanage/kubeadm/provider.go, pkg/clustermanage/kubeadm/wrapper.go, pkg/scheme/core/v1/k8s/template.go
/kind bug
The imported cluster is missing the kubectl terminal image, which prevents the service from starting
Fixes #396
```
```
```release-note
None
```
```docs
```
@x893675 @lixd
=> The imported cluster is missing the kubectl terminal image

pkg/apis/core/v1/handler.go
/kind bug
Fixes https://github.com/kubeclipper/kubeclipper/issues/405
```
```
```release-note
None
```
```docs
```
=> fix: Edit cronbackup to month-end display error

.dockerignore, .github/workflows/build-kc-image.yml, Dockerfile, deploy/etcd-sts.yaml, deploy/kc-server.yaml, hack/lib/golang.sh
/kind flake
add workflow to build kc-server image
Fixes #
```
```
```release-note
None
```
```docs
```
=> feat: add workflow to build kc-server image

api/openapi-spec/swagger.json, pkg/scheme/core/v1/cluster_types.go
/kind bug
cluster struct feild json-tag
Fixes #
```
```
```release-note
None
```
```docs
```
@x893675 @lyp256
=> fix: cluster struct feild json-tag (#413)

api/openapi-spec/swagger.json, pkg/apis/core/v1/handler.go, pkg/apis/core/v1/registry.go, pkg/models/cluster/cluster.go, pkg/models/models.go, pkg/query/query.go, pkg/query/query_test.go, pkg/server/restplus/multi_watch.go, pkg/server/restplus/multi_watch_test.go
/kind bug
support query global resource in project
Fixes #
```
add api to support query global resource in project, query global resource and project resource at the same time
```
```release-note
None
```
```docs
```
=> fix: support query global resource in project

cmd/kcctl/app/options/options.go, go.mod, go.sum, pkg/authentication/options/options.go, pkg/cli/config/template.go, pkg/cli/deploy/deploy.go, pkg/clustermanage/kubeadm/provider.go, pkg/clustermanage/kubeadm/wrapper.go, pkg/server/config.go, pkg/server/server.go
Sign-off-by: xu.jingwen <xu.jingwen@99cloud.net>
/kind feature
Fixes #419 
```
```
```release-note
```
```docs
```
=> feat: support specify password when deploy

pkg/simple/client/kc/api.go, test/e2e/cluster/cluster_aio_cert.go, test/framework/cluster/wait.go
/kind  test
Fixes #
```
```
```release-note
None
```
```docs
```
=> test: add cluster cert update e2e test

test/e2e/cluster/delete_cluster.go
Fixes #
```
```
```release-note
```
```docs
```
=> force delete cluster e2e test

pkg/simple/client/kc/api.go, test/e2e/cluster/cri_registry.go, test/framework/cluster/wait.go
Fixes #431 
```
```
```release-note
```
```docs
```
=> cri registry e2e test

pkg/cli/deploy/deploy.go, test/e2e/cluster/cluster_aio_cert.go
/kind bug
Fixes #
```
```
```release-note
```
```docs
```
=> fix: modify kc-console ca delivery node

test/e2e/cluster/cri_registry.go, test/e2e/cluster/delete_cluster.go, test/e2e/node/join_node.go, test/framework/cluster/node.go, test/framework/cluster/wait.go
/kind flake
Fixes #
```
```
```release-note
None
```
```docs
```
=> test: add join、drain node e2e test

pkg/scheme/core/v1/cri/containerd.go
/kind bug
Fixes #
```
```
```release-note
```
```docs
```
=> fix: pull pause image registry

pkg/simple/client/kc/api.go, pkg/simple/client/kc/request.go, pkg/simple/client/kc/request_test.go, test/e2e/region/framework.go, test/e2e/region/region.go
/kind flake
Fixes #
```
list region and fuzzy search
```
```release-note
None
```
```docs
```
=> test: add region e2e test

pkg/apis/core/v1/schema_test.go, pkg/apis/core/v1/utils_test.go, pkg/cli/create/create_cluster.go, pkg/constatns/constats.go, pkg/scheme/core/v1/cni/calico_test.go, pkg/scheme/core/v1/k8s/kubeadm_test.go, test/e2e/cluster/utils.go, test/framework/test_context.go
/kind design
update k8s cluster service and pod cidr
Fixes #
```
```
```release-note
None
```
```docs
```
@x893675 @lixd
=> update k8s cluster service and pod cidr

pkg/simple/client/kc/api.go, test/e2e/cluster/spec.go
/kind flake
Fixes #
```
cluster detail,check cluster、node and operation log.
```
```release-note
None
```
```docs
```
=> test: add cluster detail e2e test

test/e2e/cluster/spec.go
/kind feature
Fixes https://github.com/kubeclipper/kubeclipper/issues/75
```
```
```release-note
None
```
```docs
```
@lixd @x893675
=> add describe/update cluster e2e test

test/e2e/acl/external_user.go, test/e2e/cluster/registry.go, test/e2e/cluster/spec.go, test/e2e/cluster/utils.go, test/e2e/e2e_test.go, test/e2e/iam/framework.go, test/e2e/iam/role.go, test/e2e/iam/user.go
/area testing
Fixes #
```
```
```release-note
None
```
```docs
```
=> add online install cluster test spec

.dockerignore
/kind bug
we need .git directory when build
Fixes #
```
we need .git directory when build
```
```release-note
None
```
```docs
```
=> fix: update dockerignore

pkg/apis/core/v1/utils.go
/kind bug
Error deleting backup because deleting backup read from cluster structure.
Fixes https://github.com/kubeclipper/kubeclipper/issues/474
```
```
```release-note
None
```
```docs
```
@lixd @x893675
=> fix: Error deleting backup

pkg/cli/cluster/cluster_upgrade.go
/kind bug
Fixes #
```
```
```release-note
```
```docs
```
=> fix: cluster upgrade patch version check error

pkg/cli/cluster/cluster_upgrade.go, pkg/simple/client/kc/api.go
/kind bug
Fixes #
```
```
```release-note
```
```docs
```
=> fix: modify marked words and project exist check api

pkg/clusteroperation/operation.go, pkg/controller/operationcontroller/controller.go
/kind bug
Fixes #
```
```
```release-note
None
```
```docs
```
=> fix: automatic retry operation

pkg/apis/core/v1/handler.go, pkg/apis/core/v1/utils.go
/kind bug
Fixes #
```
```
```release-note
None
```
```docs
```
@x893675 @zhuzhenfan
=> add check whether any cluster is in use before delete backuppoint

pkg/cli/deploy/deploy.go
/kind bug
Fixes #
```
```
```release-note
None
```
```docs
```
=> fix check server running failed

pkg/scheme/core/v1/k8s/kubeadm.go, pkg/scheme/core/v1/k8s/template.go
/kind bug
Fixes #
```
```
```release-note
```
```docs
```
=> fix: create a cluster with multiple master nodes

pkg/apis/core/v1/handler.go
/kind bug
Fixes #
```
```
```release-note
```
```docs
```
=> fix: terminated operations support retry

test/api/README.md, test/api/fs_backup_recovery.yaml, test/api/s3_backup_recovery.yaml
Signed-off-by: cmycoups chen.mengyun@99cloud.net
Fixes #
```
```
```release-note
```
```docs
```
=> feat: add cluster backup and recovery api test cases

api/openapi-spec/swagger.json, pkg/apis/core/v1/handler.go, pkg/apis/core/v1/registry.go
/kind feature
Add feature for integrate with with IAAS. when delegateToCloudProvider set true,  iaas delete vm directly. kc should  skip delete operations and delete cluster and node data only
Fixes #
```
```
```release-note
None
```
```docs
```
@x893675 @lixd
=> feat: support delegate CloudProvider when delete cluster

pkg/component/nfs/nfs_test.go, pkg/component/nfs/template.go
/kind bug
The core component should be scheduled to the master node first, even if the node has a `NoSchedule` taint.
Compatible processing for each version of k8s.
Fixes #
```
```
```release-note
```
```docs
```
=> fix: update component workload tolerance and node affinity

pkg/cli/registry/registry.go
/kind bug
kcctl registry deploy bug
Fixes #
```
```
```release-note
None
```
```docs
```
@x893675 @lixd
=> fix: kcctl registry deploy bug

pkg/scheme/core/v1/cluster_types.go, pkg/scheme/core/v1/k8s/kubeadm.go, pkg/scheme/core/v1/k8s/kubeadm_step.go, pkg/scheme/core/v1/k8s/template.go
/kind bug
Fixes #
```
```
```release-note
```
```docs
```
=> fix: kubelet supports setting nodeip

pkg/cli/resource/resource.go, pkg/cli/upgrade/upgrade.go
/kind bug
Fixes #
```
```
```release-note
```
```docs
```
=> fix: optimize the kcctl upgrade and resource error print

.github/workflows/test-api.yml, test/api/README.md, test/api/template/template_cluster.yaml, test/api/template/template_nfs.yaml
Signed-off-by: Mengchenchen<meng.chenchen@99cloud.net>
Fixes #
```
```
```release-note
```
```docs
```
=> feat:add api test in workflow

test/api/list.yaml, test/api/registry/add_registry.yaml, test/api/registry/delete_registry.yaml, test/api/registry/get_edit_registry.yaml, test/api/registry/use_registry.yaml, test/api/run.py, test/api/test_cluster/check_test_cluster.yaml, test/api/test_cluster/create_test_cluster.yaml, test/api/test_cluster/delete_test_cluster.yaml
Signed-off-by: sacredartr <zhou.hao@99cloud.net>
Fixes #
```
```
```release-note
```
```docs
```
=> feat: add registry apitest and run task

pkg/controller/cronbackupcontroller/controller.go
/kind bug
cron-backup check cluster-apiserver bug
Fixes #
```
```
```release-note
None
```
```docs
```
=> fix: cron-backup check cluster-apiserver bug

test/api/access_control/role.yaml, test/api/access_control/user.yaml, test/api/list.yaml, test/api/run.py
Signed-off-by: sacredartr <zhou.hao@99cloud.net>
```docs
add access_control apitest
```
=> feat: add access_control apitest

pkg/authentication/auth/token.go, pkg/cli/create/create_cluster.go, pkg/utils/random/string.go, pkg/utils/random/string_test.go
/kind bug
在 metadata 中使用 generatename, 会偶现重复创建的情况。
当 etcd 中存在两个同样 token 的对象，之前的代码逻辑会报错
Fixes #
```
```
```release-note
Fix occasional 401 error
```
```docs
```
=> fix occasional 401 error

pkg/clustermanage/kubeadm/wrapper.go
/kind bug
external etcd cluster nano-management failure
Fixes #
```
```
```release-note
None
```
```docs
```
@x893675 @lixd
=> Fix external etcd cluster nano-management failure

pkg/cli/create/create_cluster.go, pkg/component/utils/registry.go
/kind feature
Fixes #
```
```
```release-note
The user can use --insecure-registry flag to specify remote registry when using kcctl to create a cluster.
```
```docs
```
=> add kcctl create cluster flag --insecure-registry

pkg/cli/registry/registry.go
/kind bug
Fix the bug of renaming tag of mirror
Fixes #
```
```
```release-note
None
```
```docs
```
=> Fix the bug of renaming tag of mirror

pkg/cli/registry/registry.go
/kind bug
kcctl registry remove image failed
Fixes #
```
```
```release-note
None
```
```docs
```
@lixd @x893675
=> fix: kcctl registry remove image failed

pkg/cli/join/join.go
/kind optimize
manual cherry-pick #577 
Fixes #
```
```
```release-note
none
```
```docs
```
=> add pkg flag for join cmd

pkg/cli/deploy/deploy.go, pkg/scheme/core/v1/cri/containerd.go, pkg/scheme/core/v1/cri/template.go
Fixes #
```
```
```release-note
```
```docs
```
=> fix: init config of containerd based on the cgroup version

pkg/cli/config/template.go
Fixes #
```
```
```release-note
```
```docs
```
=> fix: caddy reverse proxy cluster apiserver

pkg/cli/create/create_cluster.go
/kind feature
kcctl adds the service/pod subnet parameter
Fixes #
```
```
```release-note
None
```
```docs
```
@x893675 @lixd
=> kcctl adds the service/pod subnet parameter

pkg/cli/deploy/deploy.go, pkg/scheme/core/v1/cri/template.go
/kind bug
fix containerd config bug and kc deploy bug in unbuntu-18
Fixes #229 
```
@wu-wenxiang @lyp256 
```
```release-note
```
```docs
```
@wu-wenxiang @lyp256
=> fix containerd config bug and kc deploy bug in unbuntu-18

pkg/cli/deploy/deploy.go
/kind bug
fix kc deploy bug in unbuntu-18
Fixes #229 
```
@wu-wenxiang @lyp256 
```
```release-note
None
```
```docs
```
@wu-wenxiang @lyp256
=> fix kc deploy bug in unbuntu-18

pkg/cli/deploy/deploy.go
/kind bug
Ubuntu-22.04 synchronization time service name is `ntp.service`, so detecting it during deployment
Fixes #
```
```
```release-note
```
```docs
```
=> fix: check the ubuntu-22.04 synchronization time service

pkg/cli/deploy/deploy.go
Fixes #
```
```
```release-note
```
```docs
```
=> fix: ntp service discovery mode

Dockerfile
Fixes #
```
```
```release-note
```
```docs
```
=> fix: update alpine 3.16.3 to 3.18

pkg/apis/core/v1/handler.go, pkg/scheme/core/v1/k8s/kubeadm_step.go
/kind optimize
Fixes #
```
```
```release-note
none
```
```docs
```
=> use externalip in kubeconfig when cluster externalip is valid

pkg/models/cluster/cluster.go, pkg/models/core/configmap.go, pkg/models/iam/iam.go, pkg/models/operation/operation.go, pkg/models/platform/platformsetting.go
/kind flake
add namespace when create/update,for upgrade k8s api
Fixes #
```
add namespace when create/update,for upgrade k8s api
```
```release-note
None
```
```docs
```
=> fix: add namespace when create/update

pkg/cli/create/create_cluster.go
Fixes #https://github.com/kubeclipper/kubeclipper/issues/579
```
/assign @lixd 
```
```release-note
None
```
```docs
```
=> fix:offline arg in kcctl cluster create command

pkg/cli/create/create_cluster.go
/kind bug
kcctl create cluster default pod/svc subnet
Fixes #
```
```
```release-note
None
```
```docs
```
@x893675 @lixd
=> fix: kcctl create cluster pod/svc subnet

pkg/apis/proxy/handler.go, pkg/cli/config/template.go
/kind bug
The `/cluster` route prefix conflicts with the `kc-console` route prefix. 
Fixes #
```
```
```release-note
```
```docs
```
=> fix: update cluster proxy api prefix

pkg/simple/client/kc/scheme.go, pkg/simple/client/kc/scheme_test.go
/kind optimize
Fixes #
```
```
```release-note
none
```
```docs
```
=> optimize kcctl get cluster output

pkg/authentication/auth/auth_test.go
Fixes #
```
```
```release-note
```
```docs
```
=> chore: import packages only once

pkg/cli/registry/registry.go, pkg/utils/ipvsutil/ipvs_linux_test.go, pkg/utils/sshutils/cmd.go, pkg/utils/sshutils/ssh_v2.go, pkg/utils/sshutils/ssh_v2_test.go
1. registry deploy add flag skip-image-load
2. ssh and cmd util add exit code check
3. ssh and cmd util add log print
/kind flake
Fixes #
```
```
```release-note
None
```
```docs
```
=> fix: kcctl optimization

pkg/cli/create/create_cluster.go, pkg/scheme/core/v1/cni/utils.go, pkg/utils/ipvsutil/ipvs_linux_test.go
Fixes #
```
```
```release-note
```
```docs
```
=> fix: render calico v3.26.1 template

cmd/kcctl/app/options/options.go, pkg/cli/deploy/deploy.go
/kind flake
kcctl deploy command add kcServerHealthCheckTimeout flag to speicfy health check timeout,e.g. `--kcServerHealthCheckTimeout 60s`
Fixes #
```
```
```release-note
None
```
```docs
```
=> Fix timeout

pkg/scheme/core/v1/cri/cri.go
/kind feature
Fixes #688
```
add k8s v1.29、v1.30 support
```
```release-note
None
```
```docs
None
```
=> fix: support k8s 1.29 1.30

pkg/cli/registry/client/client.go
/kind bug
Fixes #705
```
None
```
```release-note
None
```
```docs
None
```
=> fix: registry add insecure options

pkg/simple/downloader/downloader.go
/kind bug
Fixed nil error log when unmarshal manifest.json. For example:
```log
downloader.go:306        unmarshal [/opt/kc/manifest/containerd/1.6.4/amd64/config/manifest.json] file contents failed: <nil>
```
```release-note
NONE
```
=> Fixed nil error log when unmarshal manifest.json

pkg/utils/cmdutil/cmdutil.go, pkg/utils/cmdutil/command.go
/kind feature
Show raw std error in log after executing cmd failed. It's helpful.
Before:
```log
run command failed: exit status 1
```
After:
```log
run command failed(exit status 1): foo bar baz
```
```release-note
NONE
```
=> Output raw std error after executing cmd failed

pkg/scheme/core/v1/cri/containerd.go, pkg/utils/cgroups/systemd.go
/kind bug
Fixed error `SystemdCgroup` runc config of containerd.
```toml
[plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc.options]
BinaryName = ""
CriuImagePath = ""
CriuPath = ""
CriuWorkPath = ""
IoGid = 0
IoUid = 0
NoNewKeyring = false
NoPivotRoot = false
Root = ""
ShimCgroup = ""
SystemdCgroup = true
```
> reference: <https://github.com/containerd/containerd/blob/main/docs/cri/config.md#cgroup-driver>
```release-note
NONE
```
=> Fixed error SystemdCgroup runc config of containerd

pkg/scheme/core/v1/k8s/kubeadm.go
/kind bug
Fixed nil pointer when getting nodes status by forcely new clientset.
```release-note
NONE
```
=> Fixed nil pointer when getting nodes status

go.mod, pkg/scheme/core/v1/cri/cri.go
/kind flake
Fixes #
```
```
```release-note
None
```
```docs
```
=> fix: support k8s v1.31

pkg/utils/systemctl/fallback.go, pkg/utils/systemctl/systemctl.go
/kind bug
Fixes #788
```
```
```release-note
None
```
```docs
```
=> fix: systemctl add fallback to  compatible old version

README.md, pkg/authentication/request/x509/x509_test.go
Fixes #
```
```
```release-note
None
```
```docs
```
=> fix: update badge

pkg/scheme/core/v1/cri/containerd.go
/kind design
add push capability,so that we can push image to kc-registry by nerdctl or ctr
Fixes #
```
None
```
```release-note
None
```
```docs
None
```
=> fix: registry add push capability

pkg/cli/create/create_cluster.go, pkg/cli/create/utils.go, pkg/cli/create/utils_test.go
/kind bug
Fixes #817
```
```
```release-note
None
```
```docs
None
```
=> fix: create cluster add node conflit check

pkg/scheme/core/v1/cri/cri.go
/kind feature
Fixes #
```
None
```
```release-note
None
```
```docs
None
```
=> feat: support k8s v1.33
