- pkg/scheme/core/v1/k8s/cluster.go
/kind bug
Fixes #
```
```
```release-note
None
```
```docs
```
> fix: recovery operation name repeat

- .github/workflows/build-kc.yml
/kind flake
fix build action.
Fixes #4
```
```
```release-note
None
```
```docs
```
> fix github action build

- pkg/service/service.go
Signed-off-by: Metrora <liu.chuwei@99cloud.net>
/kind flake
Fixes #
```
```
```release-note
None
```
```docs
```
> change the IDelivery interface

- pkg/apis/core/v1/handler.go
- pkg/apis/core/v1/utils.go
- pkg/apis/core/v1/utils_test.go
- pkg/scheme/core/v1/k8s/cluster.go
- pkg/simple/backupstore/filesystem.go
- pkg/simple/backupstore/s3.go
- pkg/simple/backupstore/store.go
/kind bug
Fixes #26 
```
```
```release-note
```
```docs
```
> fix backup cluster has no operation logs

- pkg/server/config.go
- pkg/server/server.go
- role.json
/kind feature
spilled permission.
Fixes #32
```
1. split permission.
2. import user、role、rolebinding from build-in config instead from the file.
```
```release-note
None
```
```docs
```
> fix: spilt permission.

- pkg/apis/core/v1/utils.go
/kind bug
Fixes #64 
```
```
```release-note
None
```
```docs
```
> fix undefined in backup recovery cluster operation log

- pkg/scheme/core/v1/cluster_types.go
- pkg/scheme/core/v1/k8s/kubeadm.go
- pkg/scheme/core/v1/k8s/kubeadm_step.go
/kind bug
Fixes #69 
```
```
```release-note
None
```
```docs
```
> feat: peel calico from the k8s installation package

- pkg/component/common/insecure_registry.go
- pkg/component/nfs/nfs.go
- pkg/component/utils/registry.go
/kind bug
Fixes #76 
```
```
```release-note
None
```
```docs
```
> fix: support independent update of CNI insecure registry

- pkg/apis/core/v1/handler.go
/kind bug
Fixes https://github.com/kubeclipper-labs/kubeclipper/issues/84
```
@x893675 @zhuzhenfan 
```
```release-note
None
```
```docs
```
> fix: update cronbackup without updating next schedule time

- hack/make-rules/genswagger.sh
- pkg/component/ctx.go
- pkg/component/nfs/i18n.go
- pkg/logger/logger.go
- pkg/utils/sshutils/scp.go
Fixes #2
```
```
```release-note
None
```
```docs
```
> fix: i18n typesetting

- .github/workflows/release.yml
/kind flake
update ci,upload to oss when add a tag
Fixes #
```
```
```release-note
None
```
```docs
```
> fix: update ci,upload to oss when add a tag.

- pkg/cli/deploy/config.go
- pkg/cli/deploy/deploy.go
/kind flake
Fixes #
```
```
```release-note
None
```
```docs
```
> update default pkg to v1.1.0

- README.md
- README_zh.md
> doc: fix region=CN cmd error & syntax errors

- cmd/kcctl/app/options/options.go
- pkg/agent/agent.go
- pkg/agent/config/config.go
- pkg/cli/clean/clean.go
- pkg/cli/config/template.go
- pkg/cli/deploy/config.go
- pkg/cli/deploy/deploy.go
- pkg/cli/deploy/deploy_test.go
- pkg/cli/drain/drain.go
- pkg/cli/join/agent.go
- pkg/cli/join/agent_test.go
- pkg/cli/join/join.go
- pkg/cli/sudo/sudo.go
- pkg/controller/clustercontroller/controller.go
- pkg/nodestatus/node_status.go
- pkg/scheme/common/well_known_labels.go
- pkg/service/task/service.go
/kind feature
add node metadata,config in  kubeclipper-agent.yaml report to kc-server by kc-agent.
Fixes #
```
1.kcctl deploy/join add --fip flags.
2.format kubeclipper-agent.yaml add metadata struct.
3.synchronization update deploy config cmd.
```
```release-note
None
```
```docs
```
> feat: add node metadata.

- pkg/scheme/core/v1/k8s/kubeadm.go
- pkg/scheme/core/v1/k8s/template.go
/kind bug
Fixes #113 
```
```
```release-note
None
```
```docs
```
> feat: update calico version

- pkg/apis/core/v1/handler.go
- pkg/apis/core/v1/utils.go
- pkg/component/ctx.go
- pkg/component/nfs/nfs.go
- pkg/scheme/core/v1/k8s/kubeadm_step.go
/kind feature
addon handling when uninstalling clusters
Fixes #119 
```
```
```release-note
None
```
```docs
```
> optimize: use addon uninstall steps when delete cluster direct

- README.md
- README_zh.md
Fixes #
```
```
```release-note
None
```
```docs
```
> docs: add features to README

- pkg/apis/core/v1/handler.go
- pkg/apis/core/v1/utils.go
- pkg/apis/core/v1/utils_test.go
- pkg/controller/cronbackupcontroller/controller.go
- pkg/controller/cronbackupcontroller/controller_test.go
/kind bug
Fixes https://github.com/kubeclipper-labs/kubeclipper/issues/110
```
```
```release-note
None
```
```docs
```
> fix: create month-end cron backup error

- Makefile
- hack/lib/golang.sh
- pkg/apis/core/v1/utils.go
- pkg/scheme/core/v1/k8s/kubeadm_step.go
- pkg/scheme/core/v1/k8s/script.go
- pkg/scheme/core/v1/k8s/script_unchage.go
Fixes #
```
Use GOTAGS=xxx make build
default build with tag kc_default
```
```release-note
None
```
```docs
```
> add build tags for inject kernel parameter

- pkg/scheme/core/v1/k8s/cluster.go
Fixes #
```
```
```release-note
```
```docs
```
> fix: import image package during cluster upgrade

- pkg/cli/create/create.go
- pkg/cli/create/create_cluster.go
- pkg/cli/create/create_role.go
- pkg/cli/create/create_user.go
- pkg/cli/delete/delete.go
- pkg/cli/join/join.go
- pkg/cli/login/login.go
- pkg/cli/registry/registry.go
- pkg/cli/resource/resource.go
/kind bug
Fixes #139
```
1.update kcctl example
2.fix kcctl registry deploy / push  cmd image push bug
3.fix kcctl registry deploy check is docker exist's language bug
```
```release-note
None
```
```docs
```
> fix: update kcctl examples

- api/openapi-spec/swagger.json
- pkg/apis/config/v1/handler.go
- pkg/apis/config/v1/registry.go
- pkg/apis/core/v1/handler.go
- pkg/apis/core/v1/registry.go
- pkg/apis/core/v1/utils_test.go
- pkg/cli/create/create_cluster.go
- pkg/scheme/core/v1/cluster_types.go
- pkg/scheme/types.go
- pkg/scheme/types_test.go
- pkg/server/server.go
- pkg/simple/client/kc/api.go
- pkg/simple/client/kc/scheme.go
- pkg/utils/strutil/strutil.go
- test/e2e/cluster/backup.go
- test/e2e/cluster/cluster_ha.go
- test/e2e/cluster/component.go
- test/e2e/cluster/recovery.go
- tools/doc-gen/main.go
/kind feature
Fixes #120 
```
```
```release-note
```
```docs
```
> feat: update componentmeta api to support component version interaction

- cmd/kcctl/app/options/options.go
- cmd/kcctl/app/root.go
- pkg/cli/upgrade/upgrade.go
/kind feature
Fixes #91 
```
```
```release-note
```
```docs
```
> upgrade kubeclipper platform or component

- pkg/server/restplus/errors.go
Fixes #150 
```
```
```release-note
None
```
```docs
```
> improve api error handle (#150)

- README.md
- README_zh.md
/kind bug
Fixes #194 
```
```
```release-note
```
```docs
```
> update the kcctl installation documentation

- pkg/cli/upgrade/upgrade.go
/kind bug
Fixes #197 
```
```
```release-note
```
```docs
```
> kc upgrade package nest

- pkg/scheme/core/v1/k8s/kubeadm.go
- pkg/scheme/core/v1/k8s/kubeadm_step.go
- pkg/scheme/core/v1/k8s/utils.go
/kind bug
Fixes #173
```
remove kubelet dir when delete cluster.
umount and delete kubelet dir.
```
```release-note
None
```
```docs
```
> fix: remove kubelet dir when delete cluster

- api/openapi-spec/swagger.json
- pkg/apis/core/v1/handler.go
- pkg/apis/core/v1/registry.go
- pkg/apis/core/v1/utils_test.go
- pkg/models/core/configmap.go
- pkg/models/core/interface.go
- pkg/scheme/core/v1/configmap_types.go
- pkg/server/config.go
- pkg/server/server.go
- pkg/simple/client/kc/api.go
- pkg/simple/client/kc/scheme.go
- tools/doc-gen/main.go
/kind feature
Fixes #
```
```
```release-note
none
```
```docs
```
> add API for configmap

- pkg/cli/deploy/deploy.go
- pkg/constatns/constats.go
- pkg/scheme/core/v1/registry.go
- pkg/server/config.go
- pkg/simple/client/kc/api.go
/kind feature
Fixes #
```
```
```release-note
None
```
```docs
```
> upload platform config after deploy

- pkg/apis/core/v1/schema.go
- pkg/apis/core/v1/utils.go
- pkg/cli/deploy/deploy.go
- pkg/scheme/core/v1/cri/containerd.go
- pkg/scheme/core/v1/cri/docker.go
- pkg/scheme/core/v1/k8s/cluster.go
- pkg/scheme/core/v1/k8s/kubeadm.go
- pkg/scheme/core/v1/k8s/kubeadm_step.go
- pkg/scheme/core/v1/k8s/node.go
- pkg/server/config.go
/kind bug
Fixes #214 
```
```
```release-note
```
```docs
```
> modify "no support" note

- go.mod
- go.sum
- pkg/cli/deploy/deploy.go
- pkg/cli/utils/download.go
- pkg/utils/sshutils/scp.go
/kind optimize
Fixes #
```
```
```release-note
Use process bar instead of log
```
```docs
```
> optimize log format

- pkg/server/config.go
/kind bug
Fixes #
```
```
```release-note
None
```
```docs
```
> fix: permissions

- pkg/apis/core/v1/handler.go
- pkg/controller/cloudpprovidercontroller/mock.go
- pkg/scheme/core/v1/cloudprovider_types.go
/kind bug
fix some provider's bug
Fixes #
```
1.provider update ignore status field
2.rename terminating to removing
3.make nil map
```
```release-note
None
```
```docs
```
> fix: provider update ignore status,rename terminating to removing

- pkg/component/common/check_csi_install.go
- pkg/component/nfs/nfs.go
/kind feature
Fixes https://github.com/kubeclipper-labs/kubeclipper/issues/238
```
```
```release-note
None
```
```docs
```
@x893675
> fix: add check install step for nfs

- README.md
- README_zh.md
Fixes #
```
```
```release-note
None
```
```docs
```
> doc: update README

- cmd/kubeclipper-server/app/options/options.go
- pkg/client/clientrest/client.go
- pkg/controller-runtime/manager/manager.go
- pkg/server/server.go
- pkg/service/staticresource/static_resource.go
/kind bug
when the http server starts, it listens to the specified interface
Fixes #245 
```
@x893675 @lyp256 
```
```release-note
None
```
```docs
```
@x893675 @lyp256
> fix: http-server start bind address update

- cmd/kubeclipper-server/app/options/options.go
- pkg/client/clientrest/client.go
- pkg/controller-runtime/manager/manager.go
- pkg/server/server.go
- pkg/service/staticresource/static_resource.go
This reverts commit 20b7c2e73072543acf7c019ebafed0d9a6ca2050.
/kind bug
Fixes #
```
pr #246 is not work
```
```release-note
none
```
```docs
```
> Revert "fix: http-server start bind address update (#246)"

- pkg/scheme/core/v1/k8s/cluster.go
/kind bug
Incorrect component code for k8s detection after cluster recovery
Fixes #253 
```
```
```release-note
None
```
```docs
```
> fix: check cluster recovery

- README.md
- README_zh.md
Fixes #
```
```
```release-note
```
```docs
```
> doc: update quick start in readme

- pkg/apis/core/v1/handler.go
- pkg/apis/core/v1/utils.go
- pkg/controller/cluster_status.go
- pkg/controller/clustercontroller/controller.go
- pkg/service/delivery/delivery.go
Fixes #216 
```
```
```release-note
```
```docs
```
> fix: update cert expiration immediately

- pkg/scheme/core/v1/k8s/kubeadm_step.go
/kind bug
Fixes #
```
```
```release-note
```
```docs
```
> fix no nodes information was passed in the flushrules step

- cmd/kcctl/app/options/options.go
- pkg/cli/clean/clean.go
- pkg/cli/deploy/agent.go
- pkg/cli/deploy/agent_test.go
- pkg/cli/deploy/deploy.go
- pkg/cli/deploy/deploy_config.go
- pkg/cli/drain/drain.go
- pkg/cli/join/join.go
- pkg/cli/proxy/deploy.go
- pkg/cli/resource/resource.go
- pkg/cli/resource/resource_test.go
- pkg/cli/upgrade/upgrade.go
- pkg/controller/cluster_status.go
- pkg/controller/clustercontroller/controller.go
- pkg/simple/client/kc/api.go
- pkg/simple/client/kc/client.go
/kind bug
Fixes #
```
1.kcctl use online deploy-config,except clean cmd，clean priority use online deploy-config,if get failed,change to use local deploy-config
2.all cmd remove deploy-config flag,except clean.
3.deploy、join、drain cmd update deploy-config，and dump a backup to local.
4.examples update
```
```release-note
None
```
```docs
```
> fix: update kcctl use online deploy config,remove local deploy config

- pkg/component/nfscsi/template.go
/kind flake
edit storageclass to support nfs rwo
Fixes #
```
```
```release-note
None
```
```docs
```
> fix: support nfs rwo

- pkg/clustermanage/kubeadm/provider.go
/kind bug
missing kubelet root-dir causes nfs deployment exception for managed clusters
Fixes #294
```
```
```release-note
None
```
```docs
```
@x893675 @lixd
> fix: import cluster missing kubelet root-dir

- pkg/cli/clean/clean.go
/kind bug
now,when kc server is not health,we can't clean it
Fixes #
```
```
```release-note
None
```
```docs
```
> fix: clean cmd add force flag to use local deploy config

- pkg/apis/core/v1/handler.go
- pkg/client/clientset/versioned/typed/core/v1/core_client.go
- pkg/client/clientset/versioned/typed/core/v1/registry.go
- pkg/client/informers/core/v1/interface.go
- pkg/client/informers/core/v1/registry.go
- pkg/controller/clustercontroller/controller.go
- pkg/scheme/core/v1/cluster_types.go
- pkg/scheme/core/v1/cri/containerd.go
- pkg/scheme/core/v1/cri/docker.go
- pkg/server/server.go
- pkg/service/delivery/delivery.go
- pkg/service/msg.go
- pkg/service/service.go
- pkg/service/task/handler.go
/kind feature
Fixes #
```
```
```release-note
None
```
```docs
```
> improve cluster controller

- pkg/apis/oauth/handler.go
/kind bug
restricted login prompt first appears at an incorrect time
Fixes #297 
```
@x893675 @qinyer 
```
```release-note
None
```
```docs
```
> fix: restricted login prompt fixed

- pkg/apis/core/v1/handler.go
/kind bug
Fixes https://github.com/kubeclipper/kubeclipper/issues/309
```
```
```release-note
```
```docs
```
@x893675 @zhuzhenfan
> fix: edit no describe backup error

- pkg/scheme/core/v1/cri/containerd.go
/kind bug
Fixes #
```
```
```release-note
None
```
```docs
```
> hotfix: create cluster by local registry

- pkg/scheme/core/v1/k8s/script_unchage.go
/kind bug
Enable ipv6 forwarding when creating a cluster, and add this feature to the code
Fixes #313 
```
```
```release-note
None
```
```docs
```
@x893675 @lixd
> fix: enable ipv6 forwarding when creating a cluster

- pkg/apis/core/v1/utils.go
- pkg/component/nfscsi/nfs_csi.go
/kind bug
Fixes #318 
```
```
```release-note
```
```docs
```
> fix: can not remove nfs-csi

- pkg/cli/registry/registry.go
Fixes #
```
```
```release-note
```
```docs
```
> update docker version

- pkg/apis/core/v1/schema.go
- pkg/apis/core/v1/utils.go
- pkg/scheme/core/v1/cri/containerd.go
- pkg/scheme/core/v1/cri/containerd_test.go
- pkg/scheme/core/v1/cri/cri.go
- pkg/scheme/core/v1/cri/docker.go
/kind bug
Fixes #
```
```
```release-note
None
```
```docs
```
> fix: worker node CRI registry init

- api/openapi-spec/swagger.json
- pkg/apis/iam/v1/handler.go
- pkg/apis/tenant/v1/handler.go
- pkg/apis/tenant/v1/registry.go
- pkg/authorization/authorizer/authorizer.go
- pkg/authorization/authorizer/interface.go
- pkg/authorization/rbac/rbac.go
- pkg/controller/projectcontroller/controller.go
- pkg/models/iam/iam.go
- pkg/models/iam/iam_test.go
- pkg/models/models.go
- pkg/models/tenant/project.go
- pkg/scheme/common/well_known_labels.go
- pkg/scheme/iam/v1/iam.go
- pkg/server/config.go
- pkg/server/filters/authorization.go
- pkg/server/request/request.go
- pkg/server/request/request_test.go
- pkg/server/server.go
- tools/doc-gen/main.go
/kind feature
update authorizer to support project scope
Fixes #
```
1.update authorizer to support project scope
2.users api response format
3.add internal role template
```
```release-note
None
```
```docs
```
> feat: update authorizer to support project scope

- pkg/apis/core/v1/handler.go
/kind bug
Fixes #
```
```
```release-note
None
```
```docs
```
> fix: create cluster CRI init

- pkg/component/nfscsi/nfs_csi.go
/kind feature
Fixes https://github.com/kubeclipper/kubeclipper/issues/335
```
```
```release-note
None
```
```docs
```
> add check step before install nfs-csi

- pkg/clustermanage/kubeadm/provider.go
/kind bug
Fixes #
```
```
```release-note
```
```docs
```
> fix the exception of deleting cloudprovider

- pkg/scheme/core/v1/cni/calico.go
- pkg/scheme/core/v1/cni/cni.go
/kind bug
Fixes #338 
```
```
```release-note
```
```docs
```
> fix: import cluster recovery bug

- pkg/clustermanage/kubeadm/provider.go
Signed-off-by: qinyang <qin.yang@99cloud.net>
/kind bug
Fixes #
```
```
```release-note
```
```docs
```
> fix import cluster label

- .github/workflows/test-aio.yml
Signed-off-by: cmyscoups chen.mengyun@99cloud.net
> ci: add e2e aio check in workflow

- api/openapi-spec/swagger.json
- pkg/apis/core/v1/handler.go
- pkg/apis/core/v1/registry.go
- pkg/apis/core/v1/utils_test.go
- pkg/apis/iam/v1/handler.go
- pkg/apis/iam/v1/registry.go
- pkg/apis/tenant/v1/handler.go
- pkg/apis/tenant/v1/registry.go
- pkg/controller/projectcontroller/controller.go
- pkg/models/iam/iam.go
- pkg/models/iam/interface.go
- pkg/models/iam/mock/mock_iam.go
- pkg/query/query.go
- pkg/scheme/common/well_known_labels.go
- pkg/server/config.go
- pkg/server/request/request.go
- pkg/server/server.go
- tools/doc-gen/main.go
Fixes #
```
```
```release-note
None
```
```docs
```
> feat: add cluster's projects scope api

- go.mod
- go.sum
- pkg/apis/core/v1/handler.go
- pkg/apis/core/v1/registry.go
- pkg/apis/core/v1/utils.go
- pkg/apis/core/v1/utils_test.go
- pkg/apis/iam/v1/handler.go
- pkg/apis/proxy/handler.go
- pkg/apis/proxy/registry.go
- pkg/apis/tenant/v1/handler.go
- pkg/authorization/authorizer/interface.go
- pkg/authorization/rbac/rbac.go
- pkg/authorization/rbac/rbac_test.go
- pkg/server/config.go
- pkg/server/filters/authorization.go
- pkg/server/request/request.go
- pkg/server/request/response.go
- pkg/server/server.go
- tools/doc-gen/main.go
/kind feature
Fixes #
```
```
```release-note
None
```
```docs
```
> feat: support kubernetes api proxy

- pkg/component/common/check_csi_install.go
/kind feature
Fixes https://github.com/kubeclipper/kubeclipper/issues/368
```
```
```release-note
None
```
```docs
```
> fix: Check csi health step is not idempotent

- go.mod
- go.sum
- pkg/apis/core/v1/handler.go
- pkg/apis/core/v1/registry.go
- pkg/apis/core/v1/utils.go
- pkg/apis/core/v1/utils_test.go
- pkg/apis/iam/v1/handler.go
- pkg/apis/proxy/handler.go
- pkg/apis/proxy/registry.go
- pkg/apis/tenant/v1/handler.go
- pkg/authorization/authorizer/interface.go
- pkg/authorization/rbac/rbac.go
- pkg/authorization/rbac/rbac_test.go
- pkg/server/config.go
- pkg/server/filters/authorization.go
- pkg/server/request/request.go
- pkg/server/request/response.go
- pkg/server/server.go
- tools/doc-gen/main.go
* feat: support kubernetes api proxy
* golint fix
* adjust func
Fixes #373
```
```
```release-note
None
```
```docs
```
> cherry-pick (#359) to master

- pkg/apis/core/v1/handler.go
- pkg/apis/core/v1/registry.go
- pkg/clustermanage/kubeadm/provider.go
- pkg/controller/projectcontroller/controller.go
- pkg/models/cluster/cluster.go
- test/e2e/cluster/cluster_ha.go
/kind feature
support specify project when create provider
Fixes #
```
```
```release-note
None
```
```docs
```
> feat: support specify project when create provider

- pkg/cli/create/create_cluster.go
- pkg/scheme/core/v1/cluster_types.go
- pkg/scheme/core/v1/k8s/kubeadm.go
- pkg/scheme/core/v1/k8s/kubeadm_step.go
/kind feature
support external ca certificate import when creating a cluster
Fixes #377 
```
kcctl create cluster --ca-cert ca.crt --ca-key ca.key
```
```release-note
None
```
```docs
```
@x893675 @lixd
> feat: support external ca certificate import when creating a cluster

- pkg/controller/cluster_status.go
/kind bug
Fixes #388 
```
```
```release-note
```
```docs
```
> optimize: add simple retry for get cluster certificate

- pkg/apis/core/v1/cri_utils.go
- pkg/apis/core/v1/handler.go
- pkg/apis/core/v1/utils.go
- pkg/apis/core/v1/utils_test.go
/kind bug
Fixes #399
```
```
```release-note
None
```
```docs
```
> cherry pick #398 to release-1.3

- pkg/clustermanage/kubeadm/wrapper.go
/kind bug
Importing a cluster kubeconfig decode
Fixes #396
```
```
```release-note
None
```
```docs
```
@x893675 @lixd
> Importing a cluster kubeconfig decode

- pkg/scheme/core/v1/k8s/node.go
/kind bug
Incorrect component image load order causes service exceptions
Fixes #407
```
```
```release-note
None
```
```docs
```
> Incorrect component image load order causes service exceptions

- api/openapi-spec/swagger.json
- pkg/scheme/core/v1/cluster_types.go
/kind bug
update cluster struct feild json-tag
Fixes #
```
```
```release-note
None
```
```docs
```
> update cluster struct json tag

- cmd/kcctl/app/options/options.go
- cmd/kubeclipper-server/app/options/options.go
- pkg/apis/core/v1/handler.go
- pkg/apis/core/v1/registry.go
- pkg/apis/core/v1/utils_test.go
- pkg/cli/config/template.go
- pkg/cli/deploy/deploy.go
- pkg/cli/login/login.go
- pkg/client/clientrest/transport.go
- pkg/controller-runtime/manager/manager.go
- pkg/server/server.go
- pkg/simple/client/kc/client.go
- pkg/simple/client/kc/options.go
- pkg/simple/client/kc/request.go
- pkg/simple/generic/options.go
- tools/doc-gen/main.go
Fixes #
```
```
```release-note
Use https by default when kcctl deploy
```
```docs
```
> feat: kcctl deploy support https

- pkg/simple/client/kc/api.go
- pkg/simple/client/kc/scheme.go
- test/e2e/cluster/template_addon.go
- test/e2e/cluster/template_cluster.go
/kind failing-test
cluster template and addon template e2e test
Fixes #
```
```
```release-note
None
```
```docs
```
@x893675 @Xvv-v
> cluster template and addon template e2e test

- pkg/cli/create/create.go
- pkg/cli/create/create_project.go
- pkg/clustermanage/kubeadm/provider.go
- pkg/clustermanage/kubeadm/wrapper.go
- pkg/component/common/image.go
/kind feature
Fixes #
```
```
```release-note
```
```docs
```
> feat: add kcctl create project command

- pkg/simple/client/kc/api.go
- test/e2e/cluster/cri_registry.go
- test/framework/cluster/wait.go
Fixes #
```
```
```release-note
```
```docs
```
> cri registry e2e test

- pkg/simple/client/kc/api.go
- pkg/simple/client/kc/scheme.go
- test/e2e/cluster/template_addon.go
- test/e2e/cluster/template_cluster.go
/kind failing-test
cluster and addon e2e test
Fixes #427 
```
```
```release-note
```
```docs
```
@x893675 @Xvv-v
> cluster and addon e2e test

- pkg/simple/client/kc/api.go
- test/e2e/cluster/cluster_aio_cert.go
- test/framework/cluster/wait.go
(cherry picked from commit 4b58042612277b602474492f8b397453b31d00a6)
/kind feature
Fixes #
```
```
```release-note
None
```
```docs
```
> test: add cluster cert update e2e test (#423)

- test/e2e/cluster/template_addon.go
- test/e2e/cluster/template_cluster.go
- test/e2e/node/drain_node.go
- test/framework/cluster/wait.go
/kind feature
Fixes #
```
```
```release-note
```
```docs
```
> force drain node e2e test

- cmd/kcctl/app/root.go
- pkg/authentication/options/options.go
- pkg/cli/cluster/cluster.go
- pkg/cli/cluster/cluster_upgrade.go
- pkg/cli/create/create_cluster.go
- pkg/cli/deploy/deploy.go
- pkg/cli/registry/registry.go
- pkg/cli/resource/resource.go
- pkg/simple/client/kc/api.go
- test/e2e/cluster/cri_registry.go
- test/e2e/cluster/delete_cluster.go
- test/e2e/cluster/upgrade.go
/kind feature
provide a command to upgrade
Fixes #
```
```
```release-note
```
```docs
```
> feat: add kcctl upgrade cluster verison command

- test/e2e/cluster/registry.go
- test/e2e/cluster/spec.go
/kind feature
Fixes #
```
```
```release-note
```
```docs
```
> update cri registry e2e test

- pkg/apis/core/v1/handler.go
/kind bug
Fixes #
```
```
```release-note
None
```
```docs
```
> fix: add empty project check in create cluster api

- pkg/simple/client/kc/api.go
- test/e2e/acl/external_user.go
- test/e2e/acl/framework.go
- test/e2e/acl/role.go
- test/e2e/acl/user.go
/kind feature
Fixes #
```
```
```release-note
```
```docs
```
> add IAM e2e test specs

- pkg/apis/iam/v1/handler.go
/kind bug
when server config with external user auth(oidc), delete external user who not assigned a role will throw a error, but user deleted successful
Fixes #
```
now,  delete multiple resource in API is not transcational, should use controller to achieve eventual consistency
```
```release-note
```
```docs
```
> fix: delete user when user not assigned a role

- test/e2e/cluster/registry.go
- test/e2e/cluster/spec.go
/kind feature
Fixes #
```
```
```release-note
```
```docs
```
> update cri registry e2e test (#452)

- cmd/kcctl/app/options/options.go
- pkg/cli/deploy/deploy.go
- pkg/simple/client/kc/api.go
- pkg/utils/strutil/strutil_test.go
- test/e2e/acl/role.go
- test/e2e/acl/user.go
/kind optimize
optimize deploy
Fixes #
```
```
```release-note
None
```
```docs
```
> change --pkg,etcd flag default value

- test/e2e/cluster/component.go
- test/e2e/cluster/spec.go
- test/framework/cluster/check.go
Fixes #
```
```
```release-note
None
```
```docs
```
> nfs component e2e test

- pkg/simple/client/kc/api.go
- pkg/simple/client/kc/scheme.go
- test/e2e/cluster/backup.go
- test/e2e/cluster/cronbackup.go
- test/e2e/cluster/spec.go
- test/framework/cluster/wait.go
/kind feature
Fixes https://github.com/kubeclipper/kubeclipper/issues/75
```
```
```release-note
None
```
```docs
```
@lixd @x893675
> update backup e2e test and add cronBackup e2e test

- pkg/cli/registry/registry.go
/kind bug
Fix a problem with kcctl registry loading kc-extension image package
Fixes #
```
```
```release-note
None
```
```docs
```
@x893675 @lixd
> Fix a problem with kcctl registry loading kc-extension image package

- pkg/scheme/core/v1/cni/calico.go
- pkg/scheme/core/v1/cni/calico_template.go
- pkg/scheme/core/v1/cri/containerd.go
- pkg/scheme/core/v1/cri/cri.go
- pkg/scheme/core/v1/cri/template.go
- pkg/scheme/core/v1/k8s/script.go
- pkg/simple/client/kc/api.go
- pkg/simple/client/kc/scheme.go
- test/e2e/cluster/cloud_provider.go
- test/e2e/cluster/spec.go
- test/framework/cluster/wait.go
- test/framework/framework.go
/kind failing-test
kubeadm cloud provider e2e test
Fixes #
```
```
```release-note
None
```
```docs
```
@x893675 @lixd
> kubeadm cloud provider e2e test

- pkg/cli/registry/registry.go
- pkg/scheme/core/v1/cni/calico.go
- pkg/scheme/core/v1/cni/calico_template.go
- pkg/scheme/core/v1/cri/containerd.go
- pkg/scheme/core/v1/cri/cri.go
- pkg/scheme/core/v1/cri/template.go
- pkg/scheme/core/v1/k8s/kubeadm_step.go
- pkg/scheme/core/v1/k8s/template.go
/kind feature
Fixes #
```
```
```release-note
```
```docs
```
> support k8s v1.24 and v1.25

- pkg/scheme/core/v1/k8s/kubeadm_test.go
- pkg/server/request/request_test.go
- pkg/utils/httputil/http_test.go
/kind feature
Fixes https://github.com/kubeclipper/kubeclipper/issues/481
```
```
```release-note
None
```
```docs
```
> add some unit-test for pkg

- pkg/client/clientrest/client_test.go
- pkg/client/clientrest/url_utils_test.go
- pkg/clusteroperation/common_test.go
- pkg/component/nfs/nfs_test.go
- pkg/component/utils/registry_test.go
- pkg/component/utils/utils_test.go
- pkg/component/validation/validation_test.go
- pkg/simple/client/kc/request_test.go
- pkg/simple/client/kc/scheme_test.go
/kind feature
Fixes https://github.com/kubeclipper/kubeclipper/issues/481
```
```
```release-note
None
```
```docs
```
> second add some unit test for pkg

- README.md
- README_zh.md
Fixes #
```
```
```release-note
```
```docs
```
> docs: update readme feature

- test/api/README.md
- test/api/create_get_cluster.yaml
Signed-off-by: cmyscoups chen.mengyun@99cloud.net
run command: gabbi-run -v all 100.100.100.100 -- test/api/create_get_cluster.yaml
> feat: add create and get cluster api test cases

- pkg/cli/deploy/deploy.go
/kind bug
The http service of kc-server is too slow to start and the login api cannot be called.
Fixes #
```
```
```release-note
None
```
```docs
```
> Increase the waiting time for the ks-server http service to start

- pkg/cli/deploy/deploy.go
/kind bug
The http service of kc-server is too slow to start and the login api cannot be called.
Fixes #
```
```
```release-note
```
```docs
```
> Increase the waiting time for the ks-server http service to start (#490)

- api/openapi-spec/swagger.json
- pkg/apis/core/v1/handler.go
- pkg/apis/core/v1/registry.go
- pkg/apis/core/v1/utils.go
- pkg/apis/core/v1/utils_test.go
- pkg/clusteroperation/node.go
- pkg/controller-runtime/manager/manager.go
- pkg/scheme/common/well_known_labels.go
- pkg/scheme/core/v1/operation_types.go
- pkg/server/server.go
- pkg/service/delivery/delivery.go
- tools/doc-gen/main.go
/kind feature
Fixes #
```
```
```release-note
```
```docs
```
> Feat interrupt operation

- cmd/kcctl/app/options/options.go
- pkg/agent/agent.go
- pkg/agent/config/config.go
- pkg/apis/core/v1/cri_utils.go
- pkg/apis/core/v1/handler.go
- pkg/apis/core/v1/utils.go
- pkg/apis/core/v1/utils_test.go
- pkg/cli/config/template.go
- pkg/cli/deploy/deploy.go
- pkg/cli/join/join.go
- pkg/clusteroperation/node.go
- pkg/clusteroperation/node_test.go
- pkg/component/ctx.go
- pkg/component/utils/utils.go
- pkg/controller/cluster_status.go
- pkg/controller/clustercontroller/controller.go
- pkg/controller/clustercontroller/metadata.go
- pkg/nodestatus/node_status.go
- pkg/scheme/core/v1/k8s/kubeadm.go
- pkg/scheme/core/v1/k8s/kubeadm_step.go
- pkg/scheme/core/v1/k8s/template.go
- pkg/scheme/core/v1/node_types.go
- pkg/scheme/core/v1/operation_types.go
- pkg/service/task/service.go
/kind feature
Fixes #
```
```
```release-note
```
```docs
```
> feat: kcctl add node-ip-detect parameter

- test/api/README.md
- test/api/add_remove_node/nfs_cluster.yaml
- test/api/add_remove_node/one_node_cluster.yaml
- test/api/add_remove_node/two_nodes_cluster.yaml
Signed-off-by: cmyscoups chen.mengyun@99cloud.net
> feat: add api test cases for add and remove nodes

- pkg/apis/core/v1/handler.go
- pkg/apis/core/v1/utils_test.go
- pkg/clusteroperation/node_test.go
- pkg/component/ctx.go
- pkg/component/nfs/nfs.go
- pkg/component/nfscsi/nfs_csi.go
- pkg/scheme/core/v1/k8s/cluster.go
- pkg/scheme/core/v1/k8s/kubeadm_step.go
- pkg/scheme/core/v1/k8s/node.go
- pkg/utils/netutil/netutil.go
- pkg/utils/netutil/netutil_test.go
- test/e2e/cluster/spec.go
/kind bug
Add high availability detection for multiple master nodes, achieving high availability of master nodes
Fixes #501 
```
```
```release-note
None
```
```docs
```
@x893675 @lixd
> Add high availability detection for multiple master nodes

- test/api/README.md
- test/api/template/template_cluster.yaml
- test/api/template/template_nfs.yaml
Signed-off-by: Mengchenchen<meng.chenchen@99cloud.net>
Fixes #
```
```
```release-note
```
```docs
```
> feat:add cluster template api testcases

- pkg/apis/core/v1/handler.go
- pkg/apis/core/v1/utils.go
- pkg/component/ctx.go
- pkg/component/nfs/nfs.go
- pkg/component/nfscsi/nfs_csi.go
- pkg/controller/clustercontroller/metadata.go
- pkg/scheme/core/v1/k8s/kubeadm_step.go
…iated
/kind bug
master node not need to be detected when the cluster is initiated
Fixes #502 
```
```
```release-note
None
```
```docs
```
@x893675 @lixd
> master node not need to be detected when the cluster is initiated

- pkg/apis/core/v1/handler.go
- pkg/clusteroperation/operation.go
- pkg/component/ctx.go
/kind bug
Fixes #
```
```
```release-note
```
```docs
```
> fix: retry termination operation

- cmd/kubeclipper-server/main.go
- pkg/component/interface.go
- pkg/component/metallb/i18n.go
- pkg/component/metallb/metallb.go
- pkg/component/metallb/metallb_test.go
- pkg/component/metallb/template.go
- pkg/component/validation/validation.go
/kind feature
Fixes #
```
```
```release-note
```
```docs
```
> feat: add load balancer addon

- pkg/component/nfs/nfs.go
- pkg/component/nfscsi/nfs_csi.go
/kind bug
too short a timeout may cause the installation to fail
Fixes #
```
```
```release-note
extend timeout period and do not ignore false
```
```docs
```
> fix: extend the install storage timeout period

- pkg/cli/join/join.go
/kind feature
The kcctl "join" command adds the ssh parameters
Fixes #
```
```
```release-note
None
```
```docs
```
> feat: The kcctl "join" command adds the ssh parameters

- pkg/query/query_test.go
- pkg/utils/sliceutil/sliceutil_test.go
- pkg/utils/wssstream/conn_test.go
/kind feature
Fixes https://github.com/kubeclipper/kubeclipper/issues/481
```
```
```release-note
None
```
```docs
```
> add some unit test in package pkg

- pkg/component/metallb/metallb.go
- pkg/component/metallb/template.go
/kind bug
In MetalLB, the IP address pool supports only CIDR prefixes and IP address ranges. So we need to limit user input.
Fixes #
```
```
```release-note
```
```docs
```
> fix: specification of metallb ip address pool configuration

- pkg/component/nfs/template.go
Change-Id: I1cde0ea79988fdf9379e5114fd3326400b970548
/kind bug
Fixes #521 
```
```
```release-note
```
```docs
```
> fix: update component workload tolerance and node affinity (#520)

- pkg/cli/utils/download.go
/kind bug
fix: update speed calculate when sendpackage,fix https://github.com/kubeclipper/kubectl/issues/1
Fixes #
```
```
```release-note
None
```
```docs
```
> fix: update speed calculate when sendpackage

- pkg/errors/errors_test.go
- pkg/logger/logger_test.go
- pkg/models/iam/utils_test.go
- pkg/models/platform/platformsetting_test.go
- pkg/nodestatus/node_status_test.go
- pkg/oplog/operation_log_test.go
/kind feature
Fixes https://github.com/kubeclipper/kubeclipper/issues/481
```
```
```release-note
None
```
```docs
```
> add some unit test for pkg

- pkg/scheme/core/v1/cluster_types.go
- pkg/scheme/core/v1/k8s/kubeadm.go
- pkg/scheme/core/v1/k8s/kubeadm_test.go
- pkg/scheme/core/v1/k8s/template.go
- pkg/scheme/core/v1/k8s/utils.go
/kind feature
node-ip as node-name
Fixes #
```
```
```release-note
None
```
```docs
```
> feat: add node-ip as node-name

- .github/workflows/test-api.yml
- test/api/README.md
Signed-off-by: Mengchenchen<meng.chenchen@99cloud.net>
Fixes #
```
```
```release-note
```
```docs
```
> feat: add test report for api test

- .github/workflows/test-api.yml
- .gitignore
- test/api/README.md
- test/api/add_remove_node/add_remove_get_node.yaml
- test/api/add_remove_node/nfs_cluster.yaml
- test/api/backup_recovery_cluster/create_backup_space.yaml
- test/api/backup_recovery_cluster/create_cluster_backup.yaml
- test/api/backup_recovery_cluster/create_scheduled_backups.yaml
- test/api/backup_recovery_cluster/delete_backup_space.yaml
- test/api/backup_recovery_cluster/delete_cluster_backup.yaml
- test/api/backup_recovery_cluster/delete_scheduled_backups.yaml
- test/api/backup_recovery_cluster/disable_enable_scheduled_backups.yaml
- test/api/backup_recovery_cluster/get_cluster_backup.yaml
- test/api/backup_recovery_cluster/get_edit_backup_space.yaml
- test/api/backup_recovery_cluster/get_edit_scheduled_backups.yaml
- test/api/backup_recovery_cluster/recovery_cluster.yaml
- test/api/registry/add_registry.yaml
- test/api/registry/delete_registry.yaml
- test/api/registry/get_edit_registry.yaml
- test/api/registry/use_registry.yaml
- test/api/run.py
- test/api/template/template_cluster.yaml
- test/api/template/template_nfs.yaml
- test/api/test_cluster/check_test_cluster.yaml
- test/api/test_cluster/create_test_cluster.yaml
- test/api/test_cluster/delete_test_cluster.yaml
Signed-off-by: sacredartr <zhou.hao@99cloud.net>
```docs
optimize the code and add err.log
```
> fix: optimize the code and add err.log

- pkg/clustermanage/kubeadm/provider.go
- pkg/scheme/core/v1/k8s/kubeadm.go
- pkg/scheme/core/v1/k8s/kubeadm_step.go
- pkg/scheme/core/v1/k8s/node.go
- pkg/utils/strutil/strutil.go
/kind bug
Fixes #
```
```
```release-note
```
```docs
```
> fix: solve the secret token of the k8s v1.24 service account

- test/api/cluster_operator/add_storage_plugin.yaml
- test/api/cluster_operator/certificate_management.yaml
- test/api/cluster_operator/cluster_upgrade.yaml
- test/api/list.yaml
- test/api/node/node_operate.yaml
- test/api/region/region_operate.yaml
Signed-off-by: Mengchenchen<meng.chenchen@99cloud.net>
Fixes #
```
```
```release-note
```
```docs
```
> feat: add api testcases for region and node

- pkg/cli/create/create_cluster.go
1. add --dns-doamin flag
2. add --ipv4-auto-detection flag
/kind feature
Fixes #
```
```
```release-note
```
```docs
```
> feat: add kcctl create cluster flags

- pkg/cli/create/create_cluster.go
* feat: add kcctl create cluster flags
1. add --dns-doamin flag
2. add --calico.ipv4-auto-detection flag
* feat: add kcctl create cluster flags
1. add --dns-doamin flag
2. add --ipv4-auto-detection flag
---------
/kind feature
Fixes #546 
```
```
```release-note
```
```docs
```
> feat: add kcctl create cluster flags (#543)

- cmd/kcctl/app/options/options.go
/kind doc
Fixes #545 
```
```
```release-note
```
```docs
```
> doc: update ip-detect flag use example

- .github/workflows/sync-script.yml
- .github/workflows/test-aio.yml
- README.md
- README_zh.md
- scripts/get-kubeclipper.sh
/kind flake
Fixes #
```
```
```release-note
None
```
```docs
```
> fix: add get-kubeclipper.sh

- .github/workflows/sync-script.yml
- .github/workflows/test-aio.yml
- README.md
- README_zh.md
- scripts/get-kubeclipper.sh
* fix: add get-kubeclipper.sh
* fix: shell check
---------
Fixes #
```
```
```release-note
None
```
```docs
```
> fix: add get-kubeclipper.sh (#554)

- scripts/get-kubeclipper.sh
Fixes #
```
```
```release-note
```
```docs
```
> feat: update kc version to v1.3.2

- pkg/clusteroperation/operation.go
- pkg/controller/clustercontroller/controller.go
- pkg/scheme/common/well_known_labels.go
- pkg/scheme/core/v1/cluster_types.go
- pkg/scheme/core/v1/k8s/cluster.go
- pkg/scheme/core/v1/k8s/kubeadm.go
- pkg/scheme/core/v1/k8s/kubeadm_step.go
- pkg/scheme/core/v1/k8s/types.go
- pkg/scheme/core/v1/operation_types.go
- pkg/service/delivery/delivery.go
/kind feature
update k8s apiserver cert SANs when update externalIP
Fixes #
```
when cluster update ,check is current api server cert SANs included all san in kc
if not,create an operation to update apiserver cert.
```
```release-note
None
```
```docs
```
> feat: update k8s apiserver cert SANs when update externalIP

- api/openapi-spec/swagger.json
- pkg/apis/core/v1/handler.go
- pkg/apis/core/v1/registry.go
- pkg/utils/sshutils/shell.go
- pkg/utils/sshutils/web_terminal.go
Fixes #570
```
```
```release-note
* suopport Pod exec over WebSocket
```
```docs
```
> feat: support exec pod for #570

- pkg/apis/proxy/handler.go
- pkg/apis/proxy/utils.go
/kind feature
Fixes #
```
POST /clusters/{cluster}/kubectl-apply
POST /clusters/{cluster}/kubectl-delete
body content type is  text/plain
```
```release-note
none
```
```docs
```
> emulate kubectl apply -f and delete -f

- pkg/cli/create/create_cluster.go
/kind feature
kcctl adds the service/pod subnet parameter
Fixes #
```
```
```release-note
None
```
```docs
```
@x893675 @lixd
> kcctl adds the service/pod subnet parameter

- scripts/get-kubeclipper.sh
Fixes #
```
```
```release-note
```
```docs
```
> ci: update default kc version from 1.3.1 to 1.3.3

- scripts/get-kubeclipper.sh
Fixes #
```
```
```release-note
```
```docs
```
> ci: update default kc version from 1.3.1 to 1.3.3 (#585)

- pkg/scheme/core/v1/k8s/cluster.go
/kind bug
fix offline upgrade
Fixes #
```
import images to all nodes, when offline upgrade
```
```release-note
None
```
```docs
```
> fix offline upgrade

- README.md
Fixes #
```
```
```release-note
```
```docs
```
> docs: add star history

- pkg/scheme/core/v1/k8s/extension.go
- pkg/scheme/core/v1/k8s/kubeadm_step.go
/kind feature
add some useful tools when deploy cluster
Fixes #
```
add some useful tools when deploy cluster, e.g.
nerdctl
nerdctl cni
openstacl-client
ansible
skopeo
netshoot
```
```release-note
None
```
```docs
```
> feat: add some useful tools when deploy cluster

- scripts/get-kubeclipper.sh
Fixes #
```
```
```release-note
```
```docs
```
> ci: update default kc version from 1.3.3 to 1.3.4

- pkg/models/cluster/cluster.go
- pkg/models/core/configmap.go
- pkg/models/iam/iam.go
- pkg/models/operation/operation.go
- pkg/models/platform/platformsetting.go
- pkg/scheme/core/v1/cluster_types.go
- pkg/scheme/core/v1/k8s/k8s.go
- pkg/scheme/core/v1/k8s/kubeadm.go
- pkg/scheme/core/v1/k8s/template.go
- pkg/scheme/core/v1/k8s/utils.go
- pkg/utils/initsystem/initsystem.go
- pkg/utils/initsystem/initsystem_unix.go
- pkg/utils/initsystem/initsystem_windows.go
/kind bug
Fixes #635
```
```
```release-note
None
```
```docs
```
> fix: cluster deploy compatible different os

- Dockerfile
/kind flake
Fixes #
```
```
```release-note
none
```
```docs
```
> fix docker image build error

- pkg/server/config.go
- pkg/server/server.go
/kind bug
Modify the kc-server startup initialization iam data, the current initialization logic is not compatible with etcd failures.
Fixes #
```
```
```release-note
None
```
```docs
```
@x893675 @lixd
> Modify kc-server boot initialization iam data

- pkg/clustermanage/kubeadm/provider.go
- pkg/component/common/chart.go
- pkg/component/utils/utils.go
- pkg/scheme/common/utils.go
- pkg/scheme/core/v1/cluster_types.go
- pkg/scheme/core/v1/cni/calico.go
- pkg/scheme/core/v1/cni/calico_template.go
- pkg/scheme/core/v1/cni/calico_test.go
- pkg/scheme/core/v1/cni/cni.go
- pkg/scheme/core/v1/cni/utils.go
- pkg/scheme/core/v1/cri/cri.go
- pkg/scheme/core/v1/k8s/extension.go
- pkg/scheme/core/v1/k8s/kubeadm_step.go
- pkg/simple/downloader/downloader.go
1. support k8s v1.26,v1.27
2. support calico v3.26.1
/kind feature
Fixes #
```
```
```release-note
none
```
```docs
```
> Support new k8s version

- pkg/component/ctx.go
/kind bug
Fixes #
```
```
```release-note
none
```
```docs
```
> fix data race

- cmd/kcctl/app/options/options.go
- pkg/cli/join/join.go
/kind feature
Fixes #
```
```
```release-note
none
```
```docs
```
> add --join-config flag for join subcmd

- pkg/apis/core/v1/handler.go
- pkg/apis/core/v1/utils.go
- pkg/cli/create/create.go
- pkg/cli/create/create_cluster.go
- pkg/cli/create/utils.go
- pkg/component/ctx.go
- pkg/scheme/common/well_known_labels.go
- pkg/scheme/core/v1/k8s/kubeadm_step.go
/kind feature
Fixes #
```
```
```release-note
none
```
```docs
```
> only install k8s component and optimize kcctl create

- pkg/cli/create/create.go
- pkg/cli/create/create_cluster.go
- pkg/scheme/core/v1/cluster_types.go
- pkg/scheme/core/v1/k8s/cluster.go
- pkg/scheme/core/v1/k8s/kubeadm.go
- pkg/scheme/core/v1/k8s/kubeadm_step.go
- pkg/scheme/core/v1/k8s/kubeadm_test.go
- pkg/scheme/core/v1/k8s/template.go
- pkg/scheme/core/v1/zz_generated.deepcopy.go
/kind feature
Fixes #
```
```
```release-note
none
```
```docs
```
> support set k8s featureGates

- .github/workflows/test-aio.yml
- pkg/server/config.go
- pkg/server/server.go
- pkg/simple/client/kc/api.go
- pkg/simple/client/kc/scheme.go
- test/e2e/cluster/spec.go
- test/framework/cluster/wait.go
- test/framework/timeouts.go
/kind bug
Modify the kc-server startup initialization iam data, the current initialization logic is not compatible with etcd failures.
Fixes #
```
```
```release-note
None
```
```docs
```
@x893675 @lixd
> Modify kc-server boot initialization iam data (#649)

- .github/workflows/build-kc.yml
- go.mod
- pkg/component/ctx.go
/kind optimize
Fixes #
```
```
```release-note
none
```
```docs
```
> optimize: bump up go version to 1.20.

- .github/workflows/build-kc.yml
/kind bug
Fixes #
```
```
```release-note
none
```
```docs
```
> fix github action build failed

- .github/workflows/sync-script.yml
- README.md
- README_zh.md
- pkg/cli/deploy/deploy.go
- scripts/get-kubeclipper.sh
Fixes #
```
```
```release-note
none
```
```docs
```
> change default version to v1.4.0

- pkg/clusteroperation/node.go
/kind bug
Fixes #
```
```
```release-note
None
```
```docs
```
> fix: add step to install extension when add node

- OWNERS
/kind flake
Fixes #
```
```
```release-note
```
```docs
None
```
> Welcome lixd to join team approvers

- pkg/cli/create/create_cluster.go
- pkg/scheme/common/well_known_labels.go
- pkg/scheme/core/v1/k8s/cluster.go
- pkg/scheme/core/v1/k8s/kubeadm.go
- pkg/scheme/core/v1/k8s/kubeadm_step.go
- pkg/scheme/core/v1/k8s/kubeadm_test.go
- pkg/scheme/core/v1/k8s/template.go
/kind feature
add ignore-preflight-errors to support some test case
Fixes #700
```
None
```
```release-note
None
```
```docs
```
> feat: support ignore-preflight-errors flag

- scripts/get-kubeclipper.sh
Fixes #
```
None
```
```release-note
None
```
```docs
None
```
> build: update default version

- pkg/cli/deploy/deploy.go
- scripts/get-kubeclipper.sh
Fixes #
```
None
```
```release-note
None
```
```docs
None
```
> fix：parse version from git info

- go.mod
- go.sum
- pkg/scheme/core/v1/cri/containerd.go
- pkg/scheme/core/v1/cri/docker.go
- pkg/utils/systemctl/systemctl.go
- pkg/utils/systemctl/systemctl_test.go
/kind feature
Add a systemctl util package and apply it to container runtimes deployment.
```release-note
NONE
```
> Add a systemctl util and apply it to container runtimes

- pkg/scheme/core/v1/k8s/kubeadm.go
/kind feature
Apply systemctl util to kubelet.
```release-note
NONE
```
> Apply systemctl util to kubelet

- pkg/scheme/core/v1/cni/calico.go
- pkg/scheme/core/v1/cni/calico_linux.go
- pkg/scheme/core/v1/k8s/kubeadm.go
- pkg/utils/netutil/netutil_linux.go
/kind feature
Convert commands to native codes in uninstalling calico.
```release-note
NONE
```
> Convert commands to native codes in uninstalling calico

- pkg/apis/core/v1/utils_test.go
- pkg/component/utils/utils.go
- pkg/scheme/core/v1/k8s/kubeadm.go
- pkg/scheme/core/v1/k8s/kubeadm_step.go
- pkg/scheme/core/v1/k8s/node.go
- tools/licfmt/licfmt.go
/kind feature
Check nodes and cluster health with kube clientset after deploying.
```release-note
NONE
```
> Check nodes and cluster health with kube clientset

- README.md
/kind bug
Fixed missing test badge: <img alt="code-check-test" src="https://github.com/kubeclipper/kubeclipper/actions/workflows/code-check-test.yml/badge.svg" />
> Fixed missing test badge

- pkg/apis/core/v1/utils_test.go
- pkg/component/utils/utils.go
- pkg/scheme/core/v1/k8s/kubeadm.go
- pkg/scheme/core/v1/k8s/kubeadm_step.go
- pkg/scheme/core/v1/k8s/node.go
- pkg/scheme/core/v1/k8s/utils.go
- pkg/utils/fileutil/file.go
- tools/licfmt/licfmt.go
/kind feature
Generate kubeconfig file with native Golang codes.
```release-note
NONE
```
> Generate kubeconfig file with native codes

- .github/workflows/build-kc.yml
- .github/workflows/check-build.yml
- .github/workflows/check-code-fmt.yml
- .github/workflows/check-test-coverage.yml
- .github/workflows/generate-kcctl-docs.yml
- .github/workflows/release.yml
- .github/workflows/test-aio.yml
- Makefile
- go.mod
- pkg/cli/resource/resource.go
- pkg/models/cluster/utils.go
- pkg/models/iam/utils.go
- pkg/scheme/core/v1/k8s/cluster.go
- pkg/scheme/core/v1/k8s/node.go
- test/framework/cluster/wait.go
- test/framework/wait.go
/kind flake
Fixes #
```
None
```
```release-note
None
```
```docs
```
> build: bump golang 1.19 to 1.21

- pkg/scheme/core/v1/k8s/kubeadm_step.go
/kind bug
bug fix
Fixes #787
```
```
```release-note
None
```
```docs
```
> fix: make k8s clientset layload

- .github/workflows/go-test-coverage.yml
/kind flake
go test coverage always canced when pr merge
Fixes #
```
```
```release-note
None
```
```docs
None
```
> fix: update workflow

- README_zh.md
Fixes #
```
```
```release-note
None
```
```docs
None
```
> fix: update badge

- pkg/apis/core/v1/handler.go
- pkg/models/cluster/cluster.go
- pkg/scheme/core/v1/container_registry_types.go
- pkg/utils/strutil/strutil.go
/kind feature
Fixes #839
```
None
```
```release-note
None
```
```docs
```
> feat: cri registry add auth field

- pkg/apis/core/v1/cri_utils.go
- pkg/apis/core/v1/handler.go
- pkg/component/utils/utils.go
- pkg/controller/clustercontroller/controller.go
- pkg/scheme/core/v1/cri/containerd.go
- pkg/scheme/core/v1/cri/containerd_test.go
- pkg/scheme/core/v1/cri/cri.go
- pkg/scheme/core/v1/cri/template.go
/kind design
Fixes #839
```
None
```
```release-note
None
```
```docs
None
```
> feat: controller support cri registry auth

- cmd/kcctl/app/options/options.go
- pkg/cli/create/create.go
- pkg/cli/create/create_cluster.go
- pkg/cli/create/create_registry.go
- pkg/cli/delete/delete.go
- pkg/cli/get/get.go
- pkg/scheme/core/v1/container_registry_types.go
- pkg/scheme/core/v1/registry.go
- pkg/simple/client/kc/api.go
feat: create cluster support specify cir registry
/kind design
Fixes #839
```
None
```
```release-note
None
```
```docs
None
```
> feat: kcctl add registry command

- pkg/scheme/core/v1/k8s/kubeadm.go
- pkg/scheme/core/v1/k8s/template.go
- pkg/scheme/core/v1/k8s/utils.go
- pkg/scheme/core/v1/k8s/utils_test.go
update cluster config apiVersion to v1beta4
/kind bug
Fixes #849
```
support k8s v1.33
```
```release-note
None
```
```docs
None
```
> feat: support k8s v1.33

- pkg/scheme/core/v1/k8s/template.go
/kind design
Fixes #851
```
None
```
```release-note
None
```
```docs
None
```
> fix: update etcd snapshot-count args to 100000

- cmd/kcctl/app/options/options.go
- cmd/kcctl/app/root.go
- pkg/cli/get/get.go
- pkg/cli/logs/logs.go
- pkg/cli/logs/logs_test.go
- pkg/scheme/core/v1/cni/calico_unsupport.go
- pkg/simple/client/kc/api.go
- pkg/simple/client/kc/scheme.go
/kind feature
add kcctl logs command to watch operation log
Fixes #869 
```
```
```release-note
None
```
```docs
None
```
> feat: kcctl add logs command

- GOVERNANCE.md
- README.md
Fixes #
```
```
```release-note
None
```
```docs
None
```
> docs: add GOVERNANCE docs

- README.md
Fixes #
```
```
```release-note
None
```
```docs
```
> docs: README add Code of Conduct

- README.md
- README_zh.md
Fixes #
```
```
```release-note
None
```
```docs
```
> docs: add openssf badge

- pkg/simple/client/kc/scheme.go
/kind cleanup
Fixes #
```
```
```release-note
None
```
```docs
```
> fix: rename var to avoid conflict

- pkg/cli/resource/resource.go
/kind bug
Fixes #883
```
```
```release-note
None
```
```docs
```
> fix: update kcctl resource list arch default value

- pkg/cli/registry/registry.go
/kind feature
kc registry support format
Fixes #
```
None
```
```release-note
None
```
```docs
None
```
> fix: registry push support tar format
